[package]
name        = "ohos-raw-binding"
version     = "0.0.1"
edition     = "2021"
license     = "MIT OR Apache-2.0"
description = "OpenHarmony's raw binding for rust"

[dependencies]
ohos-raw-sys = { workspace = true }
napi-ohos    = { workspace = true }
