[package]
name        = "ohos-display-soloist-sys"
version     = "0.0.1"
edition     = "2021"
license     = "MIT OR Apache-2.0"
description = "OpenHarmony's NativeDisplaySoloist binding for rust"

[dependencies]
