/* automatically generated by rust-bindgen 0.65.1 */

#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(clippy::missing_safety_doc)]
// bindgen's bitfield accessors transmute/cast between identical types.
#![allow(clippy::useless_transmute)]
#![allow(clippy::unnecessary_cast)]

#[allow(unused_imports)]
use ohos_native_buffer_sys::*;
#[allow(unused_imports)]
use ohos_native_window_sys::OHNativeWindow;

#[link(name = "native_image")]
unsafe extern "C" {}

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct OH_NativeImage {
    _unused: [u8; 0],
}
#[doc = " @brief The callback function of frame available.\n\n @syscap SystemCapability.Graphic.Graphic2D.NativeImage\n @param context User defined context, returned to the user in the callback function\n @since 11\n @version 1.0"]
pub type OH_OnFrameAvailable =
    ::std::option::Option<unsafe extern "C" fn(context: *mut ::std::os::raw::c_void)>;
#[doc = " @brief A listener for native image, use <b>OH_NativeImage_SetOnFrameAvailableListener</b> to register \\n\n the listener object to <b>OH_NativeImage</b>, the callback will be triggered when there is available frame\n\n @since 11\n @version 1.0"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct OH_OnFrameAvailableListener {
    #[doc = " User defined context, returned to the user in the callback function"]
    pub context: *mut ::std::os::raw::c_void,
    #[doc = " The callback function of frame available."]
    pub onFrameAvailable: OH_OnFrameAvailable,
}
extern "C" {
    #[doc = " @brief Create a <b>OH_NativeImage</b> related to an Opengl ES texture and target. \\n\n This interface needs to be used in conjunction with <b>OH_NativeImage_Destroy</b>,\n otherwise memory leaks will occur.\\n\n This interface is a non-thread-safe type interface.\\n\n\n @syscap SystemCapability.Graphic.Graphic2D.NativeImage\n @param textureId Indicates the id of the Opengl ES texture which the native image attached to.\n @param textureTarget Indicates the Opengl ES target.\n @return Returns the pointer to the <b>OH_NativeImage</b> instance created if the operation is successful, \\n\n returns <b>NULL</b> otherwise.\n @since 9\n @version 1.0"]
    pub fn OH_NativeImage_Create(textureId: u32, textureTarget: u32) -> *mut OH_NativeImage;
}
extern "C" {
    #[doc = " @brief Acquire the OHNativeWindow for the OH_NativeImage.\\n\n This interface is a non-thread-safe type interface.\\n\n\n @syscap SystemCapability.Graphic.Graphic2D.NativeImage\n @param image Indicates the pointer to a <b>OH_NativeImage</b> instance.\n @return Returns the pointer to the OHNativeWindow if the operation is successful, returns <b>NULL</b> otherwise.\n @since 9\n @version 1.0"]
    pub fn OH_NativeImage_AcquireNativeWindow(image: *mut OH_NativeImage) -> *mut OHNativeWindow;
}
extern "C" {
    #[doc = " @brief Attach the OH_NativeImage to Opengl ES context, and the Opengl ES texture is bound to the \\n\n GL_TEXTURE_EXTERNAL_OES, which will update by the OH_NativeImage.\\n\n This interface is a non-thread-safe type interface.\\n\n\n @syscap SystemCapability.Graphic.Graphic2D.NativeImage\n @param image Indicates the pointer to a <b>OH_NativeImage</b> instance.\n @param textureId Indicates the id of the Opengl ES texture which the native image attached to.\n @return Returns an error code, 0 is success, otherwise, failed.\n @since 9\n @version 1.0"]
    pub fn OH_NativeImage_AttachContext(image: *mut OH_NativeImage, textureId: u32) -> i32;
}
extern "C" {
    #[doc = " @brief Detach the OH_NativeImage from the Opengl ES context.\\n\n This interface is a non-thread-safe type interface.\\n\n\n @syscap SystemCapability.Graphic.Graphic2D.NativeImage\n @param image Indicates the pointer to a <b>OH_NativeImage</b> instance.\n @return Returns an error code, 0 is success, otherwise, failed.\n @since 9\n @version 1.0"]
    pub fn OH_NativeImage_DetachContext(image: *mut OH_NativeImage) -> i32;
}
extern "C" {
    #[doc = " @brief Update the related Opengl ES texture with the OH_NativeImage acquired buffer.\\n\n This interface needs to be called in the Opengl ES context thread.\\n\n This interface needs to be called after receiving the <b>OH_OnFrameAvailableListener</b> callback.\\n\n This interface is a non-thread-safe type interface.\\n\n\n @syscap SystemCapability.Graphic.Graphic2D.NativeImage\n @param image Indicates the pointer to a <b>OH_NativeImage</b> instance.\n @return Returns an error code, 0 is success, otherwise, failed.\n @since 9\n @version 1.0"]
    pub fn OH_NativeImage_UpdateSurfaceImage(image: *mut OH_NativeImage) -> i32;
}
extern "C" {
    #[doc = " @brief Get the timestamp of the texture image set by the most recent call to OH_NativeImage_UpdateSurfaceImage.\\n\n This interface is a non-thread-safe type interface.\\n\n\n @syscap SystemCapability.Graphic.Graphic2D.NativeImage\n @param image Indicates the pointer to a <b>OH_NativeImage</b> instance.\n @return Returns the timestamp associated to the texture image.\n @since 9\n @version 1.0"]
    pub fn OH_NativeImage_GetTimestamp(image: *mut OH_NativeImage) -> i64;
}
extern "C" {
    #[doc = " @brief Return the transform matrix of the texture image set by the most recent call to \\n\n OH_NativeImage_UpdateSurfaceImage.\n\n @syscap SystemCapability.Graphic.Graphic2D.NativeImage\n @param image Indicates the pointer to a <b>OH_NativeImage</b> instance.\n @param matrix Indicates the retrieved 4*4 transform matrix .\n @return Returns an error code, 0 is success, otherwise, failed.\n @since 9\n @version 1.0\n @deprecated since 12\n @useinstead OH_NativeImage_GetTransformMatrixV2"]
    pub fn OH_NativeImage_GetTransformMatrix(image: *mut OH_NativeImage, matrix: *mut f32) -> i32;
}
extern "C" {
    #[doc = " @brief Return the native image's surface id.\\n\n This interface is a non-thread-safe type interface.\\n\n\n @syscap SystemCapability.Graphic.Graphic2D.NativeImage\n @param image Indicates the pointer to a <b>OH_NativeImage</b> instance.\n @param surfaceId Indicates the surface id.\n @return Returns an error code, 0 is success, otherwise, failed.\n @since 11\n @version 1.0"]
    pub fn OH_NativeImage_GetSurfaceId(image: *mut OH_NativeImage, surfaceId: *mut u64) -> i32;
}
extern "C" {
    #[doc = " @brief Set the frame available callback.\\n\n Not allow calling other interfaces in the callback function.\\n\n This interface is a non-thread-safe type interface.\\n\n\n @syscap SystemCapability.Graphic.Graphic2D.NativeImage\n @param image Indicates the pointer to a <b>OH_NativeImage</b> instance.\n @param listener Indicates the callback function.\n @return Returns an error code, 0 is success, otherwise, failed.\n @since 11\n @version 1.0"]
    pub fn OH_NativeImage_SetOnFrameAvailableListener(
        image: *mut OH_NativeImage,
        listener: OH_OnFrameAvailableListener,
    ) -> i32;
}
extern "C" {
    #[doc = " @brief Unset the frame available callback.\\n\n This interface is a non-thread-safe type interface.\\n\n\n @syscap SystemCapability.Graphic.Graphic2D.NativeImage\n @param image Indicates the pointer to a <b>OH_NativeImage</b> instance.\n @return Returns an error code, 0 is success, otherwise, failed.\n @since 11\n @version 1.0"]
    pub fn OH_NativeImage_UnsetOnFrameAvailableListener(image: *mut OH_NativeImage) -> i32;
}
extern "C" {
    #[doc = " @brief Destroy the <b>OH_NativeImage</b> created by OH_NativeImage_Create, and the pointer to\n <b>OH_NativeImage</b> will be null after this operation.\\n\n This interface is a non-thread-safe type interface.\\n\n\n @syscap SystemCapability.Graphic.Graphic2D.NativeImage\n @param image Indicates the pointer to a <b>OH_NativeImage</b> pointer.\n @since 9\n @version 1.0"]
    pub fn OH_NativeImage_Destroy(image: *mut *mut OH_NativeImage);
}
extern "C" {
    #[doc = " @brief Obtains the transform matrix of the texture image by producer transform type.\\n\n The matrix will not be update until <b>OH_NativeImage_UpdateSurfaceImage</b> is called.\\n\n This interface is a non-thread-safe type interface.\\n\n\n @syscap SystemCapability.Graphic.Graphic2D.NativeImage\n @param image Indicates the pointer to a <b>OH_NativeImage</b> instance.\n @param matrix Indicates the retrieved 4*4 transform matrix .\n @return 0 - Success.\n     40001000 - image is NULL.\n @since 12\n @version 1.0"]
    pub fn OH_NativeImage_GetTransformMatrixV2(image: *mut OH_NativeImage, matrix: *mut f32)
        -> i32;
}
extern "C" {
    #[doc = " @brief Obtains the transform matrix that combines with crop rect.\n\n This API returns a transform matrix that combines the crop rect.\n Note that the matrix will not be updated until <b>OH_NativeImage_UpdateSurfaceImage</b> is called.\\n\n This interface is a non-thread-safe type interface.\\n\n\n @syscap SystemCapability.Graphic.Graphic2D.NativeImage\n @param image Indicates the pointer to a <b>OH_NativeImage</b> instance.\n @param matrix Indicates the retrieved 4*4 transform matrix .\n @return {@link NATIVE_ERROR_OK} 0 - Success.\n     {@link NATIVE_ERROR_INVALID_ARGUMENTS} 40001000 - image is NULL.\n     {@link NATIVE_ERROR_MEM_OPERATION_ERROR} 30001000 - Memory operation error, failed to get transform matrix.\n @since 15\n @version 1.0"]
    #[cfg(feature = "api-15")]
    pub fn OH_NativeImage_GetBufferMatrix(image: *mut OH_NativeImage, matrix: *mut f32) -> i32;
}
extern "C" {
    #[doc = " @brief Acquire an <b>OHNativeWindowBuffer</b> through an <b>OH_NativeImage</b> instance for content consumer.\\n\n This method can not be used at the same time with <b>OH_NativeImage_UpdateSurfaceImage</b>.\\n\n This method will create an <b>OHNativeWindowBuffer</b>.\\n\n When using <b>OHNativeWindowBuffer</b>, need to increase its reference count\n by <b>OH_NativeWindow_NativeObjectReference</b>.\\n\n When the <b>OHNativeWindowBuffer</b> is used up, its reference count needs to be decremented\n by <b>OH_NativeWindow_NativeObjectUnreference</b>.\\n\n This interface needs to be used in conjunction with <b>OH_NativeImage_ReleaseNativeWindowBuffer</b>,\n otherwise memory leaks will occur.\\n\n When the fenceFd is used up, you need to close it.\\n\n This interface is a non-thread-safe type interface.\\n\n\n @syscap SystemCapability.Graphic.Graphic2D.NativeImage\n @param image Indicates the pointer to a <b>OH_NativeImage</b> instance.\n @param nativeWindowBuffer Indicates the pointer to an <b>OHNativeWindowBuffer</b> point.\n @param fenceFd Indicates the pointer to a file descriptor handle.\n @return {@link NATIVE_ERROR_OK} 0 - Success.\n     {@link NATIVE_ERROR_INVALID_ARGUMENTS} 40001000 - image, nativeWindowBuffer, fenceFd is NULL.\n     {@link NATIVE_ERROR_NO_BUFFER} 40601000 - No buffer for consume.\n @since 12\n @version 1.0"]
    pub fn OH_NativeImage_AcquireNativeWindowBuffer(
        image: *mut OH_NativeImage,
        nativeWindowBuffer: *mut *mut OHNativeWindowBuffer,
        fenceFd: *mut ::std::os::raw::c_int,
    ) -> i32;
}
extern "C" {
    #[doc = " @brief Release the <b>OHNativeWindowBuffer</b> to the buffer queue through an\n <b>OH_NativeImage</b> instance for reuse.\\n\n The fenceFd will be closed by system.\\n\n This interface is a non-thread-safe type interface.\\n\n\n @syscap SystemCapability.Graphic.Graphic2D.NativeImage\n @param image Indicates the pointer to a <b>OH_NativeImage</b> instance.\n @param nativeWindowBuffer Indicates the pointer to an <b>OHNativeWindowBuffer</b> instance.\n @param fenceFd Indicates a file descriptor handle, which is used for timing synchronization.\n @return {@link NATIVE_ERROR_OK} 0 - Success.\n     {@link NATIVE_ERROR_INVALID_ARGUMENTS} 40001000 - image, nativeWindowBuffer is NULL.\n     {@link NATIVE_ERROR_BUFFER_STATE_INVALID} 41207000 - nativeWindowBuffer state invalid.\n     {@link NATIVE_ERROR_BUFFER_NOT_IN_CACHE} 41210000 - nativeWindowBuffer not in cache.\n @since 12\n @version 1.0"]
    pub fn OH_NativeImage_ReleaseNativeWindowBuffer(
        image: *mut OH_NativeImage,
        nativeWindowBuffer: *mut OHNativeWindowBuffer,
        fenceFd: ::std::os::raw::c_int,
    ) -> i32;
}
extern "C" {
    #[doc = " @brief Create a <b>OH_NativeImage</b> as a consumerSurface. \\n\n This interface is only used for memory rotation on the surface consumer,\n the <b>OH_NativeImage</b> will not actively perform memory rendering processing.\\n\n This method can not be used at the same time with <b>OH_NativeImage_UpdateSurfaceImage</b>.\\n\n This interface is used in conjunction with <b>OH_NativeImage_AcquireNativeWindowBuffer</b> and\n <b>OH_NativeImage_ReleaseNativeWindowBuffer</b>.\\n\n This interface needs to be used in conjunction with <b>OH_NativeImage_Destroy</b>,\n otherwise memory leaks will occur.\\n\n This interface is a non-thread-safe type interface.\\n\n\n @syscap SystemCapability.Graphic.Graphic2D.NativeImage\n @return Returns the pointer to the <b>OH_NativeImage</b> instance created if the operation is successful, \\n\n returns <b>NULL</b> otherwise.\n @since 12\n @version 1.0"]
    pub fn OH_ConsumerSurface_Create() -> *mut OH_NativeImage;
}
extern "C" {
    #[doc = " @brief Set the default usage of the <b>OH_NativeImage</b>.\\n\n This interface is a non-thread-safe type interface.\\n\n\n @syscap SystemCapability.Graphic.Graphic2D.NativeImage\n @param image Indicates the pointer to a <b>OH_NativeImage</b> instance.\n @param usage Indicates the usage of the <b>OH_NativeImage</b>.Refer to the enum <b>OH_NativeBuffer_Usage</b>.\n @return {@link NATIVE_ERROR_OK} 0 - Success.\n     {@link NATIVE_ERROR_INVALID_ARGUMENTS} 40001000 - image is NULL.\n @since 13\n @version 1.0"]
    #[cfg(feature = "api-13")]
    pub fn OH_ConsumerSurface_SetDefaultUsage(image: *mut OH_NativeImage, usage: u64) -> i32;
}
extern "C" {
    #[doc = " @brief Set the default size of the <b>OH_NativeImage</b>.\\n\n This interface is a non-thread-safe type interface.\\n\n\n @syscap SystemCapability.Graphic.Graphic2D.NativeImage\n @param image Indicates the pointer to a <b>OH_NativeImage</b> instance.\n @param width Indicates the width of the <b>OH_NativeImage</b>, and it should be greater than 0.\n @param height Indicates the height of the <b>OH_NativeImage</b>, and it should be greater than 0.\n @return {@link NATIVE_ERROR_OK} 0 - Success.\n     {@link NATIVE_ERROR_INVALID_ARGUMENTS} 40001000 - image is NULL or width, height less than or equal to 0.\n @since 13\n @version 1.0"]
    #[cfg(feature = "api-13")]
    pub fn OH_ConsumerSurface_SetDefaultSize(
        image: *mut OH_NativeImage,
        width: i32,
        height: i32,
    ) -> i32;
}
extern "C" {
    #[doc = " @brief Set the rendering in drop buffer mode of the <b>OH_NativeImage</b>.\\n\n In this mode, most of the buffers produced by the producer will be discarded,\n and the latest buffer will be selected for rending.\\n\n This mode can not simultaneously guarantee high frame rate requirements.\\n\n This interface suggest be called after the <b>OH_NativeImage_Create</b> call immediately.\\n\n This interface will only take effect when used together with the <b>OH_NativeImage_UpdateSurfaceImage</b>.\\n\n The listener callback set through <b>OH-NativeImage_SetOnFrameAvailableListener</b> will not decrease\n due to the frame loss mode being set.\\n\n This interface is a non-thread-safe type interface.\\n\n\n @syscap SystemCapability.Graphic.Graphic2D.NativeImage\n @param image Indicates the pointer to a <b>OH_NativeImage</b> instance.\n @param isOpen Indicates the switch of drop buffer mode.\n @return {@link NATIVE_ERROR_OK} 0 - Success.\n     {@link NATIVE_ERROR_INVALID_ARGUMENTS} 40001000 - image is NULL.\n @since 17\n @version 1.0"]
    #[cfg(feature = "api-17")]
    pub fn OH_NativeImage_SetDropBufferMode(image: *mut OH_NativeImage, isOpen: bool) -> i32;
}
extern "C" {
    #[doc = " @brief Create a <b>OH_NativeImage</b> related to an Opengl ES texture and target with textureId, \\n\n and choose whether to set single buffer mode.\n\n @syscap SystemCapability.Graphic.Graphic2D.NativeImage\n @param textureId Indicates the id of the Opengl ES texture which the native image attached to.\n @param textureTarget Indicates the Opengl ES target.\n @param singleBufferMode Whether to set single buffer mode.\n @return Returns the pointer to the <b>OH_NativeImage</b> instance created if the operation is successful, \\n\n returns <b>NULL</b> otherwise.\n @since 22\n @version 1.0"]
    #[cfg(feature = "api-22")]
    pub fn OH_NativeImage_CreateWithSingleBufferMode(
        textureId: u32,
        textureTarget: u32,
        singleBufferMode: bool,
    ) -> *mut OH_NativeImage;
}
extern "C" {
    #[doc = " @brief Create a <b>OH_NativeImage</b> as consumerSurface, and choose whether to set single buffer mode. \\n\n This method can not be used at the same time with <b>OH_NativeImage_UpdateSurfaceImage</b>.\\n\n This interface needs to be used in conjunction with <b>OH_NativeImage_Destroy</b>,\n otherwise memory leaks will occur.\\n\n @syscap SystemCapability.Graphic.Graphic2D.NativeImage\n @param singleBufferMode Whether to set single buffer mode.\n @return Returns the pointer to the <b>OH_NativeImage</b> instance created if the operation is successful, \\n\n returns <b>NULL</b> otherwise.\n @since 22\n @version 1.0"]
    #[cfg(feature = "api-22")]
    pub fn OH_ConsumerSurface_CreateWithSingleBufferMode(
        singleBufferMode: bool,
    ) -> *mut OH_NativeImage;
}
extern "C" {
    #[doc = " @brief Release the <b>OH_NativeImage</b> in single buffer mode.\\n\n This interface suggest be called after the producer flushes the buffer to let the buffer queue rotate, \\n\n in the single buffer mode.\n This interface is a non-thread-safe type interface.\\n\n\n @syscap SystemCapability.Graphic.Graphic2D.NativeImage\n @param image Indicates the pointer to a <b>OH_NativeImage</b> instance.\n @return {@link NATIVE_ERROR_OK} 0 - Success.\n     {@link NATIVE_ERROR_INVALID_ARGUMENTS} 40001000 - image is NULL.\n @since 22\n @version 1.0"]
    #[cfg(feature = "api-22")]
    pub fn OH_NativeImage_ReleaseTextImage(image: *mut OH_NativeImage) -> i32;
}
extern "C" {
    #[doc = " @brief Get the colorSpace of <b>OH_NativeImage</b>.\\n\n This interface is a non-thread-safe type interface.\\n\n\n @syscap SystemCapability.Graphic.Graphic2D.NativeImage\n @param image Indicates the pointer to a <b>OH_NativeImage</b> instance.\n @param colorSpace Indicates the colorSpace of <b>OH_NativeImage</b>.\n @return {@link NATIVE_ERROR_OK} 0 - Success.\n @since 22\n @version 1.0"]
    #[cfg(feature = "api-22")]
    pub fn OH_NativeImage_GetColorSpace(
        image: *mut OH_NativeImage,
        colorSpace: *mut OH_NativeBuffer_ColorSpace,
    ) -> i32;
}
extern "C" {
    #[doc = " @brief Acquire a latest <b>OHNativeWindowBuffer</b> through an <b>OH_NativeImage</b> instance for content consumer.\\n\n This method can get the latest <b>OHNativeWindowBuffer</b> and drop other <b>OHNativeWindowBuffers</b>, but consumer\n can receive the callbacks of all available buffers.\\n\n This method can not be used at the same time with <b>OH_NativeImage_UpdateSurfaceImage</b>.\\n\n This method will create an <b>OHNativeWindowBuffer</b>.\\n\n If there is a situation when <b>OHNativeWindowBuffer</b> is still used after calling\n <b>OH_NativeImage_ReleaseNativeWindowBuffer</b>, you must pay attention to the following two points.\\n\n 1) When using <b>OHNativeWindowBuffer</b>, need to increase its reference count\n by <b>OH_NativeWindow_NativeObjectReference</b>.\\n\n 2) When the <b>OHNativeWindowBuffer</b> is used up, its reference count needs to be decremented\n by <b>OH_NativeWindow_NativeObjectUnreference</b>.\\n\n This interface needs to be used in conjunction with <b>OH_NativeImage_ReleaseNativeWindowBuffer</b>,\n otherwise memory leaks will occur.\\n\n When the fenceFd is used up, you need to close it.\\n\n\n @syscap SystemCapability.Graphic.Graphic2D.NativeImage\n @param image Indicates the pointer to a <b>OH_NativeImage</b> instance.\n @param nativeWindowBuffer Indicates the pointer to an <b>OHNativeWindowBuffer</b> point.\n @param fenceFd Indicates the pointer to a file descriptor handle.\n @return {@link NATIVE_ERROR_OK} 0 - Success.\n     {@link NATIVE_ERROR_INVALID_ARGUMENTS} 40001000 - image, nativeWindowBuffer, fenceFd is NULL.\n     {@link NATIVE_ERROR_NO_BUFFER} 40601000 - No buffer for consume.\n @since 22\n @version 1.0"]
    #[cfg(feature = "api-22")]
    pub fn OH_NativeImage_AcquireLatestNativeWindowBuffer(
        image: *mut OH_NativeImage,
        nativeWindowBuffer: *mut *mut OHNativeWindowBuffer,
        fenceFd: *mut ::std::os::raw::c_int,
    ) -> i32;
}
extern "C" {
    #[doc = " @brief Check whether the texture releated to the <b>OH_NativeImage</b> has been released.\\n\n This interface is a non-thread-safe type interface.\\n\n\n @syscap SystemCapability.Graphic.Graphic2D.NativeImage\n @param image Indicates the pointer to a <b>OH_NativeImage</b> instance.\n @param isReleased Indicates whether the texture releated to the <b>OH_NativeImage</b> has been released.\n @return {@link NATIVE_ERROR_OK} 0 - Success.\n     {@link NATIVE_ERROR_INVALID_ARGUMENTS} 40001000 - image or isReleased is NULL.\n @since 23\n @version 1.0"]
    #[cfg(feature = "api-23")]
    pub fn OH_NativeImage_IsReleased(image: *mut OH_NativeImage, isReleased: *mut bool) -> i32;
}
extern "C" {
    #[doc = " @brief Clean all <b>OHNativeWindowBuffer</b> caches of the <b>OHNativeWindow</b> for the <b>OH_NativeImage</b>,\\n\n and detach the OH_NativeImage from the Opengl ES context.\\n\n This interface is a non-thread-safe type interface.\\n\n\n @syscap SystemCapability.Graphic.Graphic2D.NativeImage\n @param image Indicates the pointer to a <b>OH_NativeImage</b> instance.\n @return {@link NATIVE_ERROR_OK} 0 - Success.\n     {@link NATIVE_ERROR_INVALID_ARGUMENTS} 40001000 - image is NULL.\n @since 23\n @version 1.0"]
    #[cfg(feature = "api-23")]
    pub fn OH_NativeImage_Release(image: *mut OH_NativeImage) -> i32;
}
#[doc = " @error succeed"]
pub const OHNativeErrorCode_NATIVE_ERROR_OK: OHNativeErrorCode = 0;
#[doc = " @error memory operation error\n @since 15"]
#[cfg(feature = "api-15")]
pub const OHNativeErrorCode_NATIVE_ERROR_MEM_OPERATION_ERROR: OHNativeErrorCode = 30001000;
#[doc = " @error input invalid parameter"]
pub const OHNativeErrorCode_NATIVE_ERROR_INVALID_ARGUMENTS: OHNativeErrorCode = 40001000;
#[doc = " @error unauthorized operation"]
pub const OHNativeErrorCode_NATIVE_ERROR_NO_PERMISSION: OHNativeErrorCode = 40301000;
#[doc = " @error no idle buffer is available"]
pub const OHNativeErrorCode_NATIVE_ERROR_NO_BUFFER: OHNativeErrorCode = 40601000;
#[doc = " @error the consumer side doesn't exist"]
pub const OHNativeErrorCode_NATIVE_ERROR_NO_CONSUMER: OHNativeErrorCode = 41202000;
#[doc = " @error uninitialized"]
pub const OHNativeErrorCode_NATIVE_ERROR_NOT_INIT: OHNativeErrorCode = 41203000;
#[doc = " @error the consumer is connected"]
pub const OHNativeErrorCode_NATIVE_ERROR_CONSUMER_CONNECTED: OHNativeErrorCode = 41206000;
#[doc = " @error the buffer status did not meet expectations"]
pub const OHNativeErrorCode_NATIVE_ERROR_BUFFER_STATE_INVALID: OHNativeErrorCode = 41207000;
#[doc = " @error buffer is already in the cache queue"]
pub const OHNativeErrorCode_NATIVE_ERROR_BUFFER_IN_CACHE: OHNativeErrorCode = 41208000;
#[doc = " @error the buffer queue is full"]
pub const OHNativeErrorCode_NATIVE_ERROR_BUFFER_QUEUE_FULL: OHNativeErrorCode = 41209000;
#[doc = " @error buffer is not in the cache queue"]
pub const OHNativeErrorCode_NATIVE_ERROR_BUFFER_NOT_IN_CACHE: OHNativeErrorCode = 41210000;
#[doc = " @error the consumer is disconnected"]
pub const OHNativeErrorCode_NATIVE_ERROR_CONSUMER_DISCONNECTED: OHNativeErrorCode = 41211000;
#[doc = " @error the consumer not register listener"]
pub const OHNativeErrorCode_NATIVE_ERROR_CONSUMER_NO_LISTENER_REGISTERED: OHNativeErrorCode =
    41212000;
#[doc = " @error the current device or platform does not support it"]
pub const OHNativeErrorCode_NATIVE_ERROR_UNSUPPORTED: OHNativeErrorCode = 50102000;
#[doc = " @error unknown error, please check log"]
pub const OHNativeErrorCode_NATIVE_ERROR_UNKNOWN: OHNativeErrorCode = 50002000;
#[doc = " @error hdi interface error"]
pub const OHNativeErrorCode_NATIVE_ERROR_HDI_ERROR: OHNativeErrorCode = 50007000;
#[doc = " @error ipc send failed"]
pub const OHNativeErrorCode_NATIVE_ERROR_BINDER_ERROR: OHNativeErrorCode = 50401000;
#[doc = " @error the egl environment is abnormal"]
pub const OHNativeErrorCode_NATIVE_ERROR_EGL_STATE_UNKNOWN: OHNativeErrorCode = 60001000;
#[doc = " @error egl interface invocation failed"]
pub const OHNativeErrorCode_NATIVE_ERROR_EGL_API_FAILED: OHNativeErrorCode = 60002000;
#[doc = " @brief interface error code.\n @since 12"]
pub type OHNativeErrorCode = u32;
