include = [
  "Cargo.toml",
  "crates/**/*.toml",
  "tools/**/*.toml",
  "sys/**/*.toml",
  ".taplo.toml",
  ".typos.toml",
  "examples/**/*.toml",
]

[formatting]
align_entries = true
column_width  = 120
