[workspace]
release_always = false
changelog_update = false
dependencies_update = false
git_tag_name = "{{ package }}-v{{ version }}"
git_release_name = "{{ package }} v{{ version }}"
repo_url = "https://github.com/ohos-rs/ohos-native-bindings"
semver_check = false
publish_timeout = "30m"

# tools
[[package]]
name = "generate"
release = false
publish = false

# examples
[[package]]
name = "example"
release = false

[[package]]
name = "ark_web"
release = false

[[package]]
name = "display_soloist"
release = false

[[package]]
name = "ime"
release = false

[[package]]
name = "jsvm-example"
release = false

[[package]]
name = "napi_net_connection"
release = false

[[package]]
name = "nativerender"
release = false

[[package]]
name = "pasteboard-test"
release = false

[[package]]
name = "raw-test"
release = false

[[package]]
name = "rust-hilog"
release = false

[[package]]
name = "sensor"
release = false

[[package]]
name = "vibrator"
release = false

[[package]]
name = "vsync"
release = false
