[workspace]
release_always = false
changelog_update = false
dependencies_update = false
git_tag_name = "{{ package }}-v{{ version }}"
git_release_name = "{{ package }} v{{ version }}"
repo_url = "https://github.com/ohos-rs/ohos-native-bindings"
semver_check = false
publish_timeout = "30m"

# tools
[[package]]
name = "generate"
release = false
publish = false

# examples (all renamed to <demo>_test; none are released)
[[package]]
name = "accessibility_test"
release = false

[[package]]
name = "ability_access_control_test"
release = false

[[package]]
name = "ark_web_test"
release = false

[[package]]
name = "arkui_input_test"
release = false

[[package]]
name = "arkui_test"
release = false

[[package]]
name = "ashmem_test"
release = false

[[package]]
name = "asset_test"
release = false

[[package]]
name = "bundle_test"
release = false

[[package]]
name = "camera_test"
release = false

[[package]]
name = "display_soloist_test"
release = false

[[package]]
name = "display_test"
release = false

[[package]]
name = "drawing_test"
release = false

[[package]]
name = "fileshare_test"
release = false

[[package]]
name = "fileuri_test"
release = false

[[package]]
name = "hilog_test"
release = false

[[package]]
name = "huks_test"
release = false

[[package]]
name = "image_native_test"
release = false

[[package]]
name = "image_test"
release = false

[[package]]
name = "ime_test"
release = false

[[package]]
name = "init_test"
release = false

[[package]]
name = "jsvm_test"
release = false

[[package]]
name = "native_buffer_test"
release = false

[[package]]
name = "native_window_test"
release = false

[[package]]
name = "net_connection_test"
release = false

[[package]]
name = "net_stack_test"
release = false

[[package]]
name = "opengtx_test"
release = false

[[package]]
name = "pasteboard_test"
release = false

[[package]]
name = "qos_test"
release = false

[[package]]
name = "raw_test"
release = false

[[package]]
name = "sensor_test"
release = false

[[package]]
name = "udmf_test"
release = false

[[package]]
name = "vibrator_test"
release = false

[[package]]
name = "vsync_test"
release = false

[[package]]
name = "xcomponent_test"
release = false

[[package]]
name = "xcomponent_multi_test"
release = false
publish = false
