[package]
name        = "ohos-raw-sys"
version     = "0.1.0"
edition     = "2021"
license     = "MIT OR Apache-2.0"
description = "OpenHarmony's raw binding for rust"

[dependencies]
napi-sys-ohos = { workspace = true }
