/* automatically generated by rust-bindgen 0.65.1 */

#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(clippy::missing_safety_doc)]
// bindgen's bitfield accessors transmute/cast between identical types.
#![allow(clippy::useless_transmute)]
#![allow(clippy::unnecessary_cast)]

#[link(name = "hitrace_ndk.z")]
unsafe extern "C" {}

#[repr(C)]
#[derive(Copy, Clone, Debug, Default, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct __BindgenBitfieldUnit<Storage> {
    storage: Storage,
}
impl<Storage> __BindgenBitfieldUnit<Storage> {
    #[inline]
    pub const fn new(storage: Storage) -> Self {
        Self { storage }
    }
}
impl<Storage> __BindgenBitfieldUnit<Storage>
where
    Storage: AsRef<[u8]> + AsMut<[u8]>,
{
    #[inline]
    pub fn get_bit(&self, index: usize) -> bool {
        debug_assert!(index / 8 < self.storage.as_ref().len());
        let byte_index = index / 8;
        let byte = self.storage.as_ref()[byte_index];
        let bit_index = if cfg!(target_endian = "big") {
            7 - (index % 8)
        } else {
            index % 8
        };
        let mask = 1 << bit_index;
        byte & mask == mask
    }
    #[inline]
    pub fn set_bit(&mut self, index: usize, val: bool) {
        debug_assert!(index / 8 < self.storage.as_ref().len());
        let byte_index = index / 8;
        let byte = &mut self.storage.as_mut()[byte_index];
        let bit_index = if cfg!(target_endian = "big") {
            7 - (index % 8)
        } else {
            index % 8
        };
        let mask = 1 << bit_index;
        if val {
            *byte |= mask;
        } else {
            *byte &= !mask;
        }
    }
    #[inline]
    pub fn get(&self, bit_offset: usize, bit_width: u8) -> u64 {
        debug_assert!(bit_width <= 64);
        debug_assert!(bit_offset / 8 < self.storage.as_ref().len());
        debug_assert!((bit_offset + (bit_width as usize)) / 8 <= self.storage.as_ref().len());
        let mut val = 0;
        for i in 0..(bit_width as usize) {
            if self.get_bit(i + bit_offset) {
                let index = if cfg!(target_endian = "big") {
                    bit_width as usize - 1 - i
                } else {
                    i
                };
                val |= 1 << index;
            }
        }
        val
    }
    #[inline]
    pub fn set(&mut self, bit_offset: usize, bit_width: u8, val: u64) {
        debug_assert!(bit_width <= 64);
        debug_assert!(bit_offset / 8 < self.storage.as_ref().len());
        debug_assert!((bit_offset + (bit_width as usize)) / 8 <= self.storage.as_ref().len());
        for i in 0..(bit_width as usize) {
            let mask = 1 << i;
            let val_bit_is_set = val & mask == mask;
            let index = if cfg!(target_endian = "big") {
                bit_width as usize - 1 - i
            } else {
                i
            };
            self.set_bit(index + bit_offset, val_bit_is_set);
        }
    }
}
#[doc = " @brief Invalid <b>HiTraceId</b> instance.\n\n @syscap SystemCapability.HiviewDFX.HiTrace\n\n @since 12"]
pub const HiTraceId_Valid_HITRACE_ID_INVALID: HiTraceId_Valid = 0;
#[doc = " @brief Valid <b>HiTraceId</b> instance.\n\n @syscap SystemCapability.HiviewDFX.HiTrace\n\n @since 12"]
pub const HiTraceId_Valid_HITRACE_ID_VALID: HiTraceId_Valid = 1;
#[doc = " @brief Defines whether a <b>HiTraceId</b> instance is valid.\n\n @syscap SystemCapability.HiviewDFX.HiTrace\n\n @since 12"]
pub type HiTraceId_Valid = u32;
#[doc = " @brief Version 1.\n\n @syscap SystemCapability.HiviewDFX.HiTrace\n\n @since 12"]
pub const HiTrace_Version_HITRACE_VER_1: HiTrace_Version = 0;
#[doc = " @brief Enumerates the HiTrace version numbers.\n\n @syscap SystemCapability.HiviewDFX.HiTrace\n\n @since 12"]
pub type HiTrace_Version = u32;
#[doc = " @brief Default flag.\n\n @syscap SystemCapability.HiviewDFX.HiTrace\n\n @since 12"]
pub const HiTrace_Flag_HITRACE_FLAG_DEFAULT: HiTrace_Flag = 0;
#[doc = " @brief Both synchronous and asynchronous calls are traced. By default, only synchronous calls are traced.\n\n @syscap SystemCapability.HiviewDFX.HiTrace\n\n @since 12"]
pub const HiTrace_Flag_HITRACE_FLAG_INCLUDE_ASYNC: HiTrace_Flag = 1;
#[doc = " @brief No spans are created. By default, spans are created.\n\n @syscap SystemCapability.HiviewDFX.HiTrace\n\n @since 12"]
pub const HiTrace_Flag_HITRACE_FLAG_DONOT_CREATE_SPAN: HiTrace_Flag = 2;
#[doc = " @brief Trace points are automatically added to spans. By default, no trace point is added.\n\n @syscap SystemCapability.HiviewDFX.HiTrace\n\n @since 12"]
pub const HiTrace_Flag_HITRACE_FLAG_TP_INFO: HiTrace_Flag = 4;
#[doc = " @brief Information about the start and end of the trace task is not printed. By default, information about the\n start and end of the trace task is printed.\n\n @syscap SystemCapability.HiviewDFX.HiTrace\n\n @since 12"]
pub const HiTrace_Flag_HITRACE_FLAG_NO_BE_INFO: HiTrace_Flag = 8;
#[doc = " @brief The ID is not added to the log. By default, the ID is added to the log.\n\n @syscap SystemCapability.HiviewDFX.HiTrace\n\n @since 12"]
pub const HiTrace_Flag_HITRACE_FLAG_DONOT_ENABLE_LOG: HiTrace_Flag = 16;
#[doc = " @brief Tracing is triggered by faults.\n\n @syscap SystemCapability.HiviewDFX.HiTrace\n\n @since 12"]
pub const HiTrace_Flag_HITRACE_FLAG_FAULT_TRIGGER: HiTrace_Flag = 32;
#[doc = " @brief Trace points are added only for call chain trace between devices.\n By default, device-to-device trace points are not added.\n\n @syscap SystemCapability.HiviewDFX.HiTrace\n\n @since 12"]
pub const HiTrace_Flag_HITRACE_FLAG_D2D_TP_INFO: HiTrace_Flag = 64;
#[doc = " @brief Enumerates the HiTrace flags.\n\n @syscap SystemCapability.HiviewDFX.HiTrace\n\n @since 12"]
pub type HiTrace_Flag = u32;
#[doc = " @brief CS trace point.\n\n @syscap SystemCapability.HiviewDFX.HiTrace\n\n @since 12"]
pub const HiTrace_Tracepoint_Type_HITRACE_TP_CS: HiTrace_Tracepoint_Type = 0;
#[doc = " @brief CR trace point.\n\n @syscap SystemCapability.HiviewDFX.HiTrace\n\n @since 12"]
pub const HiTrace_Tracepoint_Type_HITRACE_TP_CR: HiTrace_Tracepoint_Type = 1;
#[doc = " @brief SS trace point.\n\n @syscap SystemCapability.HiviewDFX.HiTrace\n\n @since 12"]
pub const HiTrace_Tracepoint_Type_HITRACE_TP_SS: HiTrace_Tracepoint_Type = 2;
#[doc = " @brief SR trace point.\n\n @syscap SystemCapability.HiviewDFX.HiTrace\n\n @since 12"]
pub const HiTrace_Tracepoint_Type_HITRACE_TP_SR: HiTrace_Tracepoint_Type = 3;
#[doc = " @brief General trace point.\n\n @syscap SystemCapability.HiviewDFX.HiTrace\n\n @since 12"]
pub const HiTrace_Tracepoint_Type_HITRACE_TP_GENERAL: HiTrace_Tracepoint_Type = 4;
#[doc = " @brief Enumerates the HiTrace trace point types.\n\n @syscap SystemCapability.HiviewDFX.HiTrace\n\n @since 12"]
pub type HiTrace_Tracepoint_Type = u32;
#[doc = " @brief Default communication mode.\n\n @syscap SystemCapability.HiviewDFX.HiTrace\n\n @since 12"]
pub const HiTrace_Communication_Mode_HITRACE_CM_DEFAULT: HiTrace_Communication_Mode = 0;
#[doc = " @brief Inter-thread communication.\n\n @syscap SystemCapability.HiviewDFX.HiTrace\n\n @since 12"]
pub const HiTrace_Communication_Mode_HITRACE_CM_THREAD: HiTrace_Communication_Mode = 1;
#[doc = " @brief Inter-process communication.\n\n @syscap SystemCapability.HiviewDFX.HiTrace\n\n @since 12"]
pub const HiTrace_Communication_Mode_HITRACE_CM_PROCESS: HiTrace_Communication_Mode = 2;
#[doc = " @brief Inter-device communication.\n\n @syscap SystemCapability.HiviewDFX.HiTrace\n\n @since 12"]
pub const HiTrace_Communication_Mode_HITRACE_CM_DEVICE: HiTrace_Communication_Mode = 3;
#[doc = " @brief Enumerates the HiTrace communication modes.\n\n @syscap SystemCapability.HiviewDFX.HiTrace\n\n @since 12"]
pub type HiTrace_Communication_Mode = u32;
#[doc = " @brief Output level only for debug usage.\n\n @since 19"]
#[cfg(feature = "api-19")]
pub const HiTrace_Output_Level_HITRACE_LEVEL_DEBUG: HiTrace_Output_Level = 0;
#[doc = " @brief Output level for log version usage.\n\n @since 19"]
#[cfg(feature = "api-19")]
pub const HiTrace_Output_Level_HITRACE_LEVEL_INFO: HiTrace_Output_Level = 1;
#[doc = " @brief Output level for log version usage, with higher priority than HITRACE_LEVEL_INFO.\n\n @since 19"]
#[cfg(feature = "api-19")]
pub const HiTrace_Output_Level_HITRACE_LEVEL_CRITICAL: HiTrace_Output_Level = 2;
#[doc = " @brief Output level for nolog version usage.\n\n @since 19"]
#[cfg(feature = "api-19")]
pub const HiTrace_Output_Level_HITRACE_LEVEL_COMMERCIAL: HiTrace_Output_Level = 3;
#[doc = " @brief Output level for range limit.\n\n @since 19"]
#[cfg(feature = "api-19")]
pub const HiTrace_Output_Level_HITRACE_LEVEL_MAX: HiTrace_Output_Level = 3;
#[doc = " @brief Enumerates the HiTrace output levels. The output level threshold system parameter determines\n the minimum output trace.\n\n @since 19"]
#[cfg(feature = "api-19")]
pub type HiTrace_Output_Level = u32;
#[doc = " @brief Defines a <b>HiTraceId</b> instance.\n\n @struct HiTraceId\n\n @syscap SystemCapability.HiviewDFX.HiTrace\n\n @since 12"]
#[repr(C)]
#[repr(align(8))]
#[derive(Debug, Copy, Clone)]
pub struct HiTraceId {
    pub _bitfield_align_1: [u64; 0],
    pub _bitfield_1: __BindgenBitfieldUnit<[u8; 16usize]>,
}
impl HiTraceId {
    #[inline]
    pub fn valid(&self) -> u64 {
        unsafe { ::std::mem::transmute(self._bitfield_1.get(0usize, 1u8) as u64) }
    }
    #[inline]
    pub fn set_valid(&mut self, val: u64) {
        unsafe {
            let val: u64 = ::std::mem::transmute(val);
            self._bitfield_1.set(0usize, 1u8, val as u64)
        }
    }
    #[inline]
    pub fn ver(&self) -> u64 {
        unsafe { ::std::mem::transmute(self._bitfield_1.get(1usize, 3u8) as u64) }
    }
    #[inline]
    pub fn set_ver(&mut self, val: u64) {
        unsafe {
            let val: u64 = ::std::mem::transmute(val);
            self._bitfield_1.set(1usize, 3u8, val as u64)
        }
    }
    #[inline]
    pub fn chainId(&self) -> u64 {
        unsafe { ::std::mem::transmute(self._bitfield_1.get(4usize, 60u8) as u64) }
    }
    #[inline]
    pub fn set_chainId(&mut self, val: u64) {
        unsafe {
            let val: u64 = ::std::mem::transmute(val);
            self._bitfield_1.set(4usize, 60u8, val as u64)
        }
    }
    #[inline]
    pub fn flags(&self) -> u64 {
        unsafe { ::std::mem::transmute(self._bitfield_1.get(64usize, 12u8) as u64) }
    }
    #[inline]
    pub fn set_flags(&mut self, val: u64) {
        unsafe {
            let val: u64 = ::std::mem::transmute(val);
            self._bitfield_1.set(64usize, 12u8, val as u64)
        }
    }
    #[inline]
    pub fn spanId(&self) -> u64 {
        unsafe { ::std::mem::transmute(self._bitfield_1.get(76usize, 26u8) as u64) }
    }
    #[inline]
    pub fn set_spanId(&mut self, val: u64) {
        unsafe {
            let val: u64 = ::std::mem::transmute(val);
            self._bitfield_1.set(76usize, 26u8, val as u64)
        }
    }
    #[inline]
    pub fn parentSpanId(&self) -> u64 {
        unsafe { ::std::mem::transmute(self._bitfield_1.get(102usize, 26u8) as u64) }
    }
    #[inline]
    pub fn set_parentSpanId(&mut self, val: u64) {
        unsafe {
            let val: u64 = ::std::mem::transmute(val);
            self._bitfield_1.set(102usize, 26u8, val as u64)
        }
    }
    #[inline]
    pub fn new_bitfield_1(
        valid: u64,
        ver: u64,
        chainId: u64,
        flags: u64,
        spanId: u64,
        parentSpanId: u64,
    ) -> __BindgenBitfieldUnit<[u8; 16usize]> {
        let mut __bindgen_bitfield_unit: __BindgenBitfieldUnit<[u8; 16usize]> = Default::default();
        __bindgen_bitfield_unit.set(0usize, 1u8, {
            let valid: u64 = unsafe { ::std::mem::transmute(valid) };
            valid as u64
        });
        __bindgen_bitfield_unit.set(1usize, 3u8, {
            let ver: u64 = unsafe { ::std::mem::transmute(ver) };
            ver as u64
        });
        __bindgen_bitfield_unit.set(4usize, 60u8, {
            let chainId: u64 = unsafe { ::std::mem::transmute(chainId) };
            chainId as u64
        });
        __bindgen_bitfield_unit.set(64usize, 12u8, {
            let flags: u64 = unsafe { ::std::mem::transmute(flags) };
            flags as u64
        });
        __bindgen_bitfield_unit.set(76usize, 26u8, {
            let spanId: u64 = unsafe { ::std::mem::transmute(spanId) };
            spanId as u64
        });
        __bindgen_bitfield_unit.set(102usize, 26u8, {
            let parentSpanId: u64 = unsafe { ::std::mem::transmute(parentSpanId) };
            parentSpanId as u64
        });
        __bindgen_bitfield_unit
    }
}
#[doc = " @brief Defines the callback type used in trace status switch event.\n     The value of traceStatus indicates the current trace status.\n\n @param traceStatus The current trace status, true for open, false for close.\n @since 22"]
#[cfg(feature = "api-22")]
pub type OH_HiTrace_TraceEventListener =
    ::std::option::Option<unsafe extern "C" fn(traceStatus: bool)>;
extern "C" {
    #[doc = " @brief Starts tracing of a process.\n\n This API starts tracing, creates a <b>HiTraceId</b> instance, and sets it to the TLS of the calling thread.\n This API works only when it is called for the first time.\n\n @param name Pointer to a process name.\n @param flags Trace flag.\n @return Returns the created <b>HiTraceId</b> instance.\n\n @syscap SystemCapability.HiviewDFX.HiTrace\n\n @since 12"]
    pub fn OH_HiTrace_BeginChain(
        name: *const ::std::os::raw::c_char,
        flags: ::std::os::raw::c_int,
    ) -> HiTraceId;
}
extern "C" {
    #[doc = " @brief Ends tracing and clears the <b>HiTraceId</b> instance of the calling thread from the TLS.\n\n\n @syscap SystemCapability.HiviewDFX.HiTrace\n\n @since 12"]
    pub fn OH_HiTrace_EndChain();
}
extern "C" {
    #[doc = " @brief Obtains the trace ID of the calling thread from the TLS.\n\n\n @return Returns the trace ID of the calling thread. If the calling thread does not have a trace ID,\n an invalid trace ID is returned.\n\n @syscap SystemCapability.HiviewDFX.HiTrace\n\n @since 12"]
    pub fn OH_HiTrace_GetId() -> HiTraceId;
}
extern "C" {
    #[doc = " @brief Sets the trace ID of the calling thread. If the ID is invalid, no operation is performed.\n\n This API sets a <b>HiTraceId</b> instance to the TLS of the calling thread.\n\n @param id Trace ID to set.\n\n @syscap SystemCapability.HiviewDFX.HiTrace\n\n @since 12"]
    pub fn OH_HiTrace_SetId(id: *const HiTraceId);
}
extern "C" {
    #[doc = " @brief Clears the trace ID of the calling thread and invalidates it.\n\n This API clears the <b>HiTraceId</b> instance in the TLS of the calling thread.\n\n @syscap SystemCapability.HiviewDFX.HiTrace\n\n @since 12"]
    pub fn OH_HiTrace_ClearId();
}
extern "C" {
    #[doc = " @brief Creates a span ID based on the trace ID of the calling thread.\n\n This API generates a new span and corresponding <b>HiTraceId</b> instance based on the <b>HiTraceId</b>\n instance in the TLS of the calling thread.\n\n @return Returns a valid span ID. If span creation is not allowed, the ID of the calling thread is traced.\n\n @syscap SystemCapability.HiviewDFX.HiTrace\n\n @since 12"]
    pub fn OH_HiTrace_CreateSpan() -> HiTraceId;
}
extern "C" {
    #[doc = " @brief Prints HiTrace information, including the trace ID.\n\n This API prints trace point information, including the communication mode, trace point type, timestamp, and span.\n\n @param mode Communication mode for the trace point.\n @param type Trace point type.\n @param id Trace ID.\n @param fmt Custom information to print.\n\n @syscap SystemCapability.HiviewDFX.HiTrace\n\n @since 12"]
    pub fn OH_HiTrace_Tracepoint(
        mode: HiTrace_Communication_Mode,
        type_: HiTrace_Tracepoint_Type,
        id: *const HiTraceId,
        fmt: *const ::std::os::raw::c_char,
        ...
    );
}
extern "C" {
    #[doc = " @brief Initializes a <b>HiTraceId</b> structure.\n\n @param id ID of the <b>HiTraceId</b> structure to be initialized.\n\n @syscap SystemCapability.HiviewDFX.HiTrace\n\n @since 12"]
    pub fn OH_HiTrace_InitId(id: *mut HiTraceId);
}
extern "C" {
    #[doc = " @brief Creates a <b>HiTraceId</b> structure based on a byte array.\n\n @param id ID of the <b>HiTraceId</b> structure to be created.\n @param pIdArray Byte array.\n @param len Length of the byte array.\n\n @syscap SystemCapability.HiviewDFX.HiTrace\n\n @since 12"]
    pub fn OH_HiTrace_IdFromBytes(
        id: *mut HiTraceId,
        pIdArray: *const u8,
        len: ::std::os::raw::c_int,
    );
}
extern "C" {
    #[doc = " @brief Checks whether a <b>HiTraceId</b> instance is valid.\n\n\n @param id <b>HiTraceId</b> instance to check.\n @return Returns <b>true</b> if the <b>HiTraceId</b> instance is valid; returns <b>false</b> otherwise.\n\n @syscap SystemCapability.HiviewDFX.HiTrace\n\n @since 12"]
    pub fn OH_HiTrace_IsIdValid(id: *const HiTraceId) -> bool;
}
extern "C" {
    #[doc = " @brief Checks whether the specified trace flag in a <b>HiTraceId</b> instance is enabled.\n\n\n @param id <b>HiTraceId</b> instance to check.\n @param flag Specified trace flag.\n @return Returns <b>true</b> if the specified trace flag is enabled; returns <b>false</b> otherwise.\n\n @syscap SystemCapability.HiviewDFX.HiTrace\n\n @since 12"]
    pub fn OH_HiTrace_IsFlagEnabled(id: *const HiTraceId, flag: HiTrace_Flag) -> bool;
}
extern "C" {
    #[doc = " @brief Enables the specified trace flag in a <b>HiTraceId</b> instance.\n\n\n @param id <b>HiTraceId</b> instance for which you want to enable the specified trace flag.\n @param flag Specified trace flag.\n\n @syscap SystemCapability.HiviewDFX.HiTrace\n\n @since 12"]
    pub fn OH_HiTrace_EnableFlag(id: *const HiTraceId, flag: HiTrace_Flag);
}
extern "C" {
    #[doc = " @brief Obtains the trace flag set in a <b>HiTraceId</b> instance.\n\n @param id <b>HiTraceId</b> instance.\n\n @return Returns the trace flag set in the specified <b>HiTraceId</b> instance.\n\n @syscap SystemCapability.HiviewDFX.HiTrace\n\n @since 12"]
    pub fn OH_HiTrace_GetFlags(id: *const HiTraceId) -> ::std::os::raw::c_int;
}
extern "C" {
    #[doc = " @brief Sets the trace flag for a <b>HiTraceId</b> instance.\n\n @param id <b>HiTraceId</b> instance.\n @param flags Trace flag to set.\n\n @syscap SystemCapability.HiviewDFX.HiTrace\n\n @since 12"]
    pub fn OH_HiTrace_SetFlags(id: *mut HiTraceId, flags: ::std::os::raw::c_int);
}
extern "C" {
    #[doc = " @brief Obtains the trace chain ID.\n\n @param id <b>HiTraceId</b> instance for which you want to obtain the trace chain ID.\n\n @return Returns the trace chain ID of the specified <b>HiTraceId</b> instance.\n\n @syscap SystemCapability.HiviewDFX.HiTrace\n\n @since 12"]
    pub fn OH_HiTrace_GetChainId(id: *const HiTraceId) -> u64;
}
extern "C" {
    #[doc = " @brief Sets the trace chain ID to a <b>HiTraceId</b> instance\n\n @param id <b>HiTraceId</b> instance.\n @param chainId Trace chain ID to set.\n\n @syscap SystemCapability.HiviewDFX.HiTrace\n\n @since 12"]
    pub fn OH_HiTrace_SetChainId(id: *mut HiTraceId, chainId: u64);
}
extern "C" {
    #[doc = " @brief Obtains the span ID in a <b>HiTraceId</b> instance.\n\n @param id <b>HiTraceId</b> instance for which you want to obtain the span ID.\n\n @return Returns the span ID in the specified <b>HiTraceId</b> instance.\n\n @syscap SystemCapability.HiviewDFX.HiTrace\n\n @since 12"]
    pub fn OH_HiTrace_GetSpanId(id: *const HiTraceId) -> u64;
}
extern "C" {
    #[doc = " @brief Sets the span ID in a <b>HiTraceId</b> instance.\n\n @param id <b>HiTraceId</b> instance for which you want to set the span ID.\n @param spanId Span ID to set.\n\n @syscap SystemCapability.HiviewDFX.HiTrace\n\n @since 12"]
    pub fn OH_HiTrace_SetSpanId(id: *mut HiTraceId, spanId: u64);
}
extern "C" {
    #[doc = " @brief Obtains the parent span ID in a <b>HiTraceId</b> instance.\n\n @param id <b>HiTraceId</b> instance for which you want to obtain the parent span ID.\n\n @return Returns the parent span ID in the specified <b>HiTraceId</b> instance.\n\n @syscap SystemCapability.HiviewDFX.HiTrace\n\n @since 12"]
    pub fn OH_HiTrace_GetParentSpanId(id: *const HiTraceId) -> u64;
}
extern "C" {
    #[doc = " @brief Sets the parent span ID in a <b>HiTraceId</b> instance.\n\n @param id <b>HiTraceId</b> instance for which you want to set the parent span ID.\n @param parentSpanId Parent span ID to set.\n\n @syscap SystemCapability.HiviewDFX.HiTrace\n\n @since 12"]
    pub fn OH_HiTrace_SetParentSpanId(id: *mut HiTraceId, parentSpanId: u64);
}
extern "C" {
    #[doc = " @brief Converts a <b>HiTraceId</b> instance into a byte array for caching or communication.\n\n @param id <b>HiTraceId</b> instance to be converted.\n @param pIdArray Byte array.\n @param len Length of the byte array.\n\n @return Returns the length of the byte array after conversion.\n\n @syscap SystemCapability.HiviewDFX.HiTrace\n\n @since 12"]
    pub fn OH_HiTrace_IdToBytes(
        id: *const HiTraceId,
        pIdArray: *mut u8,
        len: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    #[doc = " @brief Marks the start of a synchronous trace task.\n\n The <b>OH_HiTrace_StartTrace</b> and <b>OH_HiTrace_FinishTrace</b> APIs must be used in pairs.\n The two APIs can be used in nested mode. The stack data structure is used for matching during trace data parsing.\n\n @param name Name of a trace task.\n\n @syscap SystemCapability.HiviewDFX.HiTrace\n @since 10"]
    pub fn OH_HiTrace_StartTrace(name: *const ::std::os::raw::c_char);
}
extern "C" {
    #[doc = " @brief Marks the end of a synchronous trace task.\n\n This API must be used with <b>OH_HiTrace_StartTrace</b> in pairs. During trace data parsing, the system matches\n it with the <b>OH_HiTrace_StartTrace</b> API recently invoked in the service process.\n\n @syscap SystemCapability.HiviewDFX.HiTrace\n @since 10"]
    pub fn OH_HiTrace_FinishTrace();
}
extern "C" {
    #[doc = " @brief Marks the start of an asynchronous trace task.\n\n This API is called to implement performance trace in asynchronous manner. The start and end of an asynchronous\n trace task do not occur in sequence. Therefore, a unique <b>taskId</b> is required to ensure proper data parsing.\n It is passed as an input parameter for the asynchronous API.\n This API is used with <b>OH_HiTrace_FinishAsyncTrace</b> in pairs. The two APIs that have the same name and\n task ID together form an asynchronous timeslice trace task.\n If multiple trace tasks with the same name need to be performed at the same time or a trace task needs to be\n performed multiple times concurrently, different task IDs must be specified in <b>OH_HiTrace_StartTrace</b>.\n If the trace tasks with the same name are not performed at the same time, the same taskId can be used.\n\n @param name Name of the asynchronous trace task.\n @param taskId ID of the asynchronous trace task. The start and end of an asynchronous trace task do not occur in\n sequence. Therefore, the start and end of an asynchronous trace need to be matched based on the task name and the\n unique task ID together.\n\n @syscap SystemCapability.HiviewDFX.HiTrace\n @since 10"]
    pub fn OH_HiTrace_StartAsyncTrace(name: *const ::std::os::raw::c_char, taskId: i32);
}
extern "C" {
    #[doc = " @brief Marks the end of an asynchronous trace task.\n\n This API is called in the callback function after an asynchronous trace is complete.\n It is used with <b>OH_HiTrace_StartAsyncTrace</b> in pairs. Its name and task ID must be the same as those of\n <b>OH_HiTrace_StartAsyncTrace</b>.\n\n @param name Name of the asynchronous trace task.\n @param taskId ID of the asynchronous trace task. The start and end of an asynchronous trace task do not occur in\n sequence. Therefore, the start and end of an asynchronous trace need to be matched based on the task name and the\n unique task ID together.\n\n @syscap SystemCapability.HiviewDFX.HiTrace\n @since 10"]
    pub fn OH_HiTrace_FinishAsyncTrace(name: *const ::std::os::raw::c_char, taskId: i32);
}
extern "C" {
    #[doc = " @brief Traces the value change of an integer variable based on its name.\n\n This API can be executed for multiple times to trace the value change of a given integer variable at different\n time points.\n\n @param name Name of the integer variable. It does not need to be the same as the real variable name.\n @param count Integer value. Generally, an integer variable can be passed.\n\n @syscap SystemCapability.HiviewDFX.HiTrace\n @since 10"]
    pub fn OH_HiTrace_CountTrace(name: *const ::std::os::raw::c_char, count: i64);
}
extern "C" {
    #[doc = " @brief Marks the start of a synchronous trace task with output level control.\n\n The <b>OH_HiTrace_StartTraceEx</b> and <b>OH_HiTrace_FinishTraceEx</b> APIs must be used in pairs.\n The two APIs can be used in nested mode. The stack data structure is used for matching during trace data parsing.\n\n @param level Trace output priority level.\n @param name Name of the synchronous trace task.\n @param customArgs key=value pair, multiple pairs use comma as separator.\n @since 19"]
    #[cfg(feature = "api-19")]
    pub fn OH_HiTrace_StartTraceEx(
        level: HiTrace_Output_Level,
        name: *const ::std::os::raw::c_char,
        customArgs: *const ::std::os::raw::c_char,
    );
}
extern "C" {
    #[doc = " @brief Marks the end of a synchronous trace task with output level control.\n\n This API must be used with <b>OH_HiTrace_StartTraceEx</b> in pairs. The two APIs, which have the same level,\n form an synchronous timeslice trace task.\n During trace data parsing, the system matches it with the most recent <b>OH_HiTrace_StartTraceEx</b> API\n invocation in the service process.\n\n @param level Trace output priority level.\n @since 19"]
    #[cfg(feature = "api-19")]
    pub fn OH_HiTrace_FinishTraceEx(level: HiTrace_Output_Level);
}
extern "C" {
    #[doc = " @brief Marks the start of an asynchronous trace task with output level control.\n\n This API is called to implement performance trace in asynchronous manner. The start and end of an asynchronous\n trace task do not occur in sequence. Therefore, a unique <b>taskId</b> is required to ensure proper data parsing.\n It is passed as an input parameter for the asynchronous API.\n This API is used with <b>OH_HiTrace_FinishAsyncTraceEx</b> in pairs. The two APIs, which have the same level,\n name, and task ID, form an asynchronous timeslice trace task.\n If customCategory is specified, the trace slice will be grouped and displayed together with other trace slices\n with the same customCategory.\n If multiple trace tasks with the same name need to be performed at the same time or a trace task needs to be\n performed multiple times concurrently, different task IDs must be specified in <b>OH_HiTrace_StartAsyncTraceEx</b>.\n If the trace tasks with the same name are not performed at the same time, the same taskId can be used.\n Different processes's taskId do not interfere.\n\n @param level Trace output priority level.\n @param name Name of the asynchronous trace task.\n @param taskId ID of the asynchronous trace task.\n @param customCategory Label used to aggregate the asynchronous trace.\n @param customArgs key=value pair, multiple pairs use comma as separator.\n @since 19"]
    #[cfg(feature = "api-19")]
    pub fn OH_HiTrace_StartAsyncTraceEx(
        level: HiTrace_Output_Level,
        name: *const ::std::os::raw::c_char,
        taskId: i32,
        customCategory: *const ::std::os::raw::c_char,
        customArgs: *const ::std::os::raw::c_char,
    );
}
extern "C" {
    #[doc = " @brief Marks the end of an asynchronous trace task with output level control.\n\n This API is called in the callback function after an asynchronous trace is complete.\n It is used with <b>OH_HiTrace_StartAsyncTraceEx</b> in pairs. Its level, name, and task ID must be\n the same as those of <b>OH_HiTrace_StartAsyncTraceEx</b>.\n\n @param level Trace output priority level.\n @param name Name of the asynchronous trace task.\n @param taskId ID of the asynchronous trace task.\n @since 19"]
    #[cfg(feature = "api-19")]
    pub fn OH_HiTrace_FinishAsyncTraceEx(
        level: HiTrace_Output_Level,
        name: *const ::std::os::raw::c_char,
        taskId: i32,
    );
}
extern "C" {
    #[doc = " @brief Traces the value change of an integer variable based on its name with output level control.\n\n This API can be executed for multiple times to trace the value change of a given integer variable at different\n time points.\n\n @param level Trace output priority level.\n @param name Name of the integer variable. It does not need to be the same as the real variable name.\n @param count Integer value. Generally, an integer variable can be passed.\n @since 19"]
    #[cfg(feature = "api-19")]
    pub fn OH_HiTrace_CountTraceEx(
        level: HiTrace_Output_Level,
        name: *const ::std::os::raw::c_char,
        count: i64,
    );
}
extern "C" {
    #[doc = " @brief Get the trace output status of the calling process.\n\n @return Returns whether the calling process is allowed to output trace.\n @since 19"]
    #[cfg(feature = "api-19")]
    pub fn OH_HiTrace_IsTraceEnabled() -> bool;
}
extern "C" {
    #[doc = " @brief Register trace switch notification callback.\n\n Register a callback function to execute specific trace-related behavior when trace\n status is changed. The current status will be passed as 0 for off or 1 for on as callback function\n paramter representing current trace status. The maximum number of registered callback functions is 10.\n\n @param callback The callback function to be invoked when trace status is changed.\n @return The callback registeration status.\n     >= 0: Successfully registered and callback index used for unregister.\n    -1: Reaches max number of callback functions.\n    -2: Invalid parameter.\n @since 22"]
    #[cfg(feature = "api-22")]
    pub fn OH_HiTrace_RegisterTraceListener(callback: OH_HiTrace_TraceEventListener) -> i32;
}
extern "C" {
    #[doc = " @brief Unregister trace switch notification callback.\n\n Unregister the callback function registeration for trace switch\n notification with provided registered callback function index.\n\n @param index The callback function index to be unregistered.\n @return The callback unregisteration status.\n     0: Success.\n    -1: Callback function with target index has not been registered.\n    -2: Invalid index range.\n @since 22"]
    #[cfg(feature = "api-22")]
    pub fn OH_HiTrace_UnregisterTraceListener(index: i32) -> i32;
}
