/* automatically generated by rust-bindgen 0.65.1 */

#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(clippy::missing_safety_doc)]
// bindgen's bitfield accessors transmute/cast between identical types.
#![allow(clippy::useless_transmute)]
#![allow(clippy::unnecessary_cast)]

#[link(name = "os_account_ndk")]
unsafe extern "C" {}

#[doc = " @error Operation is successful."]
pub const OsAccount_ErrCode_OS_ACCOUNT_ERR_OK: OsAccount_ErrCode = 0;
#[doc = " @error Internal error."]
pub const OsAccount_ErrCode_OS_ACCOUNT_ERR_INTERNAL_ERROR: OsAccount_ErrCode = 12300001;
#[doc = " @error Invalid parameter."]
pub const OsAccount_ErrCode_OS_ACCOUNT_ERR_INVALID_PARAMETER: OsAccount_ErrCode = 12300002;
#[doc = " @brief Enumerates the error codes.\n\n @since 12"]
pub type OsAccount_ErrCode = u32;
extern "C" {
    #[doc = " @brief Gets the name of the OS account to which the caller process belongs.\n\n @param buffer The name character array which should have space for the name and the terminating character ('\\0').\n @param buffer_size The size of the name character array.\n @return {@link OS_ACCOUNT_ERR_OK} Indicates successful;<br>\n         {@link OS_ACCOUNT_ERR_INTERNAL_ERROR} Indicates the internal error.<br>\n         {@link OS_ACCOUNT_ERR_INVALID_PARAMETER} Indicates the <i>buffer</i> is NULL pointer or the size of the name,\n         including the terminating character ('\\0'), is larger than <i>buffer_size</i>;\n @syscap SystemCapability.Account.OsAccount\n @since 12"]
    pub fn OH_OsAccount_GetName(
        buffer: *mut ::std::os::raw::c_char,
        buffer_size: usize,
    ) -> OsAccount_ErrCode;
}
