/* automatically generated by rust-bindgen 0.65.1 */

#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(clippy::missing_safety_doc)]
// bindgen's bitfield accessors transmute/cast between identical types.
#![allow(clippy::useless_transmute)]
#![allow(clippy::unnecessary_cast)]

#[link(name = "usb_ndk.z")]
#[link(name = "ddk_base.z")]
unsafe extern "C" {}

#[doc = " @brief Defines the shared memory created by using <b>OH_DDK_CreateAshmem</b>.\\n\n A buffer for the shared memory provides better performance.\n\n @since 12"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct DDK_Ashmem {
    #[doc = " File descriptor of the shared memory."]
    pub ashmemFd: i32,
    #[doc = " Buffer address."]
    pub address: *const u8,
    #[doc = " Buffer size."]
    pub size: u32,
    #[doc = " Offset of the used buffer. The default value is 0, which indicates that there is no offset\\n\n and the buffer starts from the specified address."]
    pub offset: u32,
    #[doc = " Length of the used buffer. By default, the value is equal to the size, which indicates that\\n\n the entire buffer is used."]
    pub bufferLength: u32,
    #[doc = " Length of the transferred data."]
    pub transferredLength: u32,
}
#[doc = " @error Operation success"]
pub const DDK_RetCode_DDK_SUCCESS: DDK_RetCode = 0;
#[doc = " @error Operation failed"]
pub const DDK_RetCode_DDK_FAILURE: DDK_RetCode = 28600001;
#[doc = " @error Invalid parameter"]
pub const DDK_RetCode_DDK_INVALID_PARAMETER: DDK_RetCode = 28600002;
#[doc = " @error Invalid operation"]
pub const DDK_RetCode_DDK_INVALID_OPERATION: DDK_RetCode = 28600003;
#[doc = " @error Null pointer exception"]
pub const DDK_RetCode_DDK_NULL_PTR: DDK_RetCode = 28600004;
#[doc = " @brief Enumerates the error codes used in the Base DDK.\n\n @since 12"]
pub type DDK_RetCode = u32;
#[doc = " @brief Setup data for control transfer. It corresponds to <b>Setup Data</b> in the USB protocol.\n\n @since 10\n @version 1.0"]
#[repr(C)]
#[repr(align(8))]
#[derive(Debug, Copy, Clone)]
pub struct UsbControlRequestSetup {
    #[doc = " Request type."]
    pub bmRequestType: u8,
    #[doc = " Request command."]
    pub bRequest: u8,
    #[doc = " Its meaning varies according to the request."]
    pub wValue: u16,
    #[doc = " It is usually used to transfer the index or offset.\\n\n Its meaning varies according to the request."]
    pub wIndex: u16,
    #[doc = " Data length. If data is transferred,\\n\n this field indicates the number of transferred bytes."]
    pub wLength: u16,
}
#[doc = " @brief Standard device descriptor, corresponding to <b>Standard Device Descriptor</b> in the USB protocol.\n\n @since 10\n @version 1.0"]
#[repr(C)]
#[repr(align(8))]
#[derive(Debug, Copy, Clone)]
pub struct UsbDeviceDescriptor {
    #[doc = " Size of the descriptor, in bytes."]
    pub bLength: u8,
    #[doc = " Descriptor type."]
    pub bDescriptorType: u8,
    #[doc = " USB protocol release number."]
    pub bcdUSB: u16,
    #[doc = " Device class code allocated by the USB-IF."]
    pub bDeviceClass: u8,
    #[doc = " Device subclass code allocated by USB-IF. The value is limited by that of bDeviceClass."]
    pub bDeviceSubClass: u8,
    #[doc = " Protocol code allocated by USB-IF. The value is limited by that of bDeviceClass and bDeviceSubClass."]
    pub bDeviceProtocol: u8,
    #[doc = " Maximum packet size of endpoint 0. Only values 8, 16, 32, and 64 are valid."]
    pub bMaxPacketSize0: u8,
    #[doc = " Vendor ID allocated by USB-IF."]
    pub idVendor: u16,
    #[doc = " Product ID allocated by the vendor."]
    pub idProduct: u16,
    #[doc = " Device release number."]
    pub bcdDevice: u16,
    #[doc = " Index of the string descriptor that describes the vendor."]
    pub iManufacturer: u8,
    #[doc = " Index of the string descriptor that describes the product."]
    pub iProduct: u8,
    #[doc = " Index of the string descriptor that describes the device SN."]
    pub iSerialNumber: u8,
    #[doc = " Configuration quantity."]
    pub bNumConfigurations: u8,
}
#[doc = " @brief Standard configuration descriptor, corresponding to <b>Standard Configuration Descriptor</b>\\n\n in the USB protocol.\n\n @since 10\n @version 1.0"]
#[repr(C, packed)]
#[derive(Debug, Copy, Clone)]
pub struct UsbConfigDescriptor {
    #[doc = " Size of the descriptor, in bytes."]
    pub bLength: u8,
    #[doc = " Descriptor type."]
    pub bDescriptorType: u8,
    #[doc = " Total length of the configuration descriptor, including the configuration, interface, endpoint,\\n\n and class- or vendor-specific descriptors."]
    pub wTotalLength: u16,
    #[doc = " Number of interfaces supported by the configuration."]
    pub bNumInterfaces: u8,
    #[doc = " Configuration index, which is used to select the configuration."]
    pub bConfigurationValue: u8,
    #[doc = " Index of the string descriptor that describes the configuration."]
    pub iConfiguration: u8,
    #[doc = " Configuration attributes, including the power mode and remote wakeup."]
    pub bmAttributes: u8,
    #[doc = " Maximum power consumption of the bus-powered USB device, in 2 mA."]
    pub bMaxPower: u8,
}
#[doc = " @brief Standard interface descriptor, corresponding to <b>Standard Interface Descriptor</b>\n in the USB protocol.\n\n @since 10\n @version 1.0"]
#[repr(C, packed)]
#[derive(Debug, Copy, Clone)]
pub struct UsbInterfaceDescriptor {
    #[doc = " Size of the descriptor, in bytes."]
    pub bLength: u8,
    #[doc = " Descriptor type."]
    pub bDescriptorType: u8,
    #[doc = " Interface number."]
    pub bInterfaceNumber: u8,
    #[doc = " Value used to select the alternate setting of the interface."]
    pub bAlternateSetting: u8,
    #[doc = " Number of endpoints (excluding endpoint 0) used by the interface."]
    pub bNumEndpoints: u8,
    #[doc = " Interface class code allocated by the USB-IF."]
    pub bInterfaceClass: u8,
    #[doc = " Interface subclass code allocated by USB-IF. The value is limited by that of bInterfaceClass."]
    pub bInterfaceSubClass: u8,
    #[doc = " Protocol code allocated by USB-IF. The value is limited by that of bInterfaceClass and bInterfaceSubClass."]
    pub bInterfaceProtocol: u8,
    #[doc = " Index of the string descriptor that describes the interface."]
    pub iInterface: u8,
}
#[doc = " @brief Standard endpoint descriptor, corresponding to <b>Standard Endpoint Descriptor</b> in the USB protocol.\n\n @since 10\n @version 1.0"]
#[repr(C, packed)]
#[derive(Debug, Copy, Clone)]
pub struct UsbEndpointDescriptor {
    #[doc = " Size of the descriptor, in bytes."]
    pub bLength: u8,
    #[doc = " Descriptor type."]
    pub bDescriptorType: u8,
    #[doc = " Endpoint address, including the endpoint number and endpoint direction."]
    pub bEndpointAddress: u8,
    #[doc = " Endpoint attributes, including the transfer type, synchronization type, and usage type."]
    pub bmAttributes: u8,
    #[doc = " Maximum packet size supported by an endpoint."]
    pub wMaxPacketSize: u16,
    #[doc = " Interval for polling endpoints for data transfer."]
    pub bInterval: u8,
    #[doc = " Refresh rate for audio devices."]
    pub bRefresh: u8,
    #[doc = " Endpoint synchronization address for audio devices."]
    pub bSynchAddress: u8,
}
#[doc = " @brief Endpoint descriptor.\n\n @since 10\n @version 1.0"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct UsbDdkEndpointDescriptor {
    #[doc = " Standard endpoint descriptor."]
    pub endpointDescriptor: UsbEndpointDescriptor,
    #[doc = " Unresolved descriptor, including class- or vendor-specific descriptors."]
    pub extra: *const u8,
    #[doc = " Length of the unresolved descriptor."]
    pub extraLength: u32,
}
#[doc = " @brief Interface descriptor.\n\n @since 10\n @version 1.0"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct UsbDdkInterfaceDescriptor {
    #[doc = " Standard interface descriptor."]
    pub interfaceDescriptor: UsbInterfaceDescriptor,
    #[doc = " Endpoint descriptor contained in the interface."]
    pub endPoint: *mut UsbDdkEndpointDescriptor,
    #[doc = " Unresolved descriptor, including class- or vendor-specific descriptors."]
    pub extra: *const u8,
    #[doc = " Length of the unresolved descriptor."]
    pub extraLength: u32,
}
#[doc = " @brief USB interface.\n\n @since 10\n @version 1.0"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct UsbDdkInterface {
    #[doc = " Number of alternate settings of the interface."]
    pub numAltsetting: u8,
    #[doc = " Alternate setting of the interface."]
    pub altsetting: *mut UsbDdkInterfaceDescriptor,
}
#[doc = " @brief Configuration descriptor.\n\n @since 10\n @version 1.0"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct UsbDdkConfigDescriptor {
    #[doc = " Standard configuration descriptor."]
    pub configDescriptor: UsbConfigDescriptor,
    #[doc = " Interfaces contained in the configuration."]
    pub interface: *mut UsbDdkInterface,
    #[doc = " Unresolved descriptor, including class- or vendor-specific descriptors."]
    pub extra: *const u8,
    #[doc = " Length of the unresolved descriptor."]
    pub extraLength: u32,
}
#[doc = " @brief Request pipe.\n\n @since 10\n @version 1.0"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct UsbRequestPipe {
    #[doc = " Interface operation handle."]
    pub interfaceHandle: u64,
    #[doc = " Timeout duration, in milliseconds."]
    pub timeout: u32,
    #[doc = " Endpoint address."]
    pub endpoint: u8,
}
#[doc = " @brief Device memory map created by calling <b>OH_Usb_CreateDeviceMemMap</b>.\\n\n A buffer using the device memory map can provide better performance.\n\n @since 10\n @version 1.0"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct UsbDeviceMemMap {
    #[doc = " Buffer address."]
    pub address: *mut u8,
    #[doc = " Buffer size."]
    pub size: usize,
    #[doc = " Offset of the used buffer. The default value is 0, indicating that there is no offset\\n\n and the buffer starts from the specified address."]
    pub offset: u32,
    #[doc = " Length of the used buffer. By default, the value is equal to the size, indicating that\\n\n the entire buffer is used."]
    pub bufferLength: u32,
    #[doc = " Length of the transferred data."]
    pub transferedLength: u32,
}
#[doc = " @error The operation is successful."]
pub const UsbDdkErrCode_USB_DDK_SUCCESS: UsbDdkErrCode = 0;
#[doc = " @error The operation failed.\n  @deprecated since 16"]
pub const UsbDdkErrCode_USB_DDK_FAILED: UsbDdkErrCode = -1;
#[doc = " @error Permission denied.\n  @since 14"]
#[cfg(feature = "api-14")]
pub const UsbDdkErrCode_USB_DDK_NO_PERM: UsbDdkErrCode = 201;
#[doc = " @error Invalid parameter."]
pub const UsbDdkErrCode_USB_DDK_INVALID_PARAMETER: UsbDdkErrCode = 401;
#[doc = " @error Memory-related error, for example, insufficient memory, memory data copy failure,\\n\n or memory application failure."]
pub const UsbDdkErrCode_USB_DDK_MEMORY_ERROR: UsbDdkErrCode = 27400001;
#[doc = " @error Null pointer exception\n  @deprecated since 16"]
pub const UsbDdkErrCode_USB_DDK_NULL_PTR: UsbDdkErrCode = -5;
#[doc = " @error Device busy.\n  @deprecated since 16"]
pub const UsbDdkErrCode_USB_DDK_DEVICE_BUSY: UsbDdkErrCode = -6;
#[doc = " @error Invalid operation."]
pub const UsbDdkErrCode_USB_DDK_INVALID_OPERATION: UsbDdkErrCode = 27400002;
#[doc = " @error Device I/O operation failed.\n  @since 14"]
#[cfg(feature = "api-14")]
pub const UsbDdkErrCode_USB_DDK_IO_FAILED: UsbDdkErrCode = 27400003;
#[doc = " @error Transmission timeout."]
pub const UsbDdkErrCode_USB_DDK_TIMEOUT: UsbDdkErrCode = 27400004;
#[doc = " @brief Defines error codes for USB DDK.\n\n @since 10\n @version 1.0"]
pub type UsbDdkErrCode = i32;
#[doc = " @brief all usb devices.\n\n @since 18"]
#[cfg(feature = "api-18")]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Usb_DeviceArray {
    #[doc = " device id array"]
    pub deviceIds: *mut u64,
    #[doc = " Number of devices. If the value is 0, no device exists"]
    pub num: u32,
}
extern "C" {
    #[doc = " @brief Initializes the DDK.\n\n @permission ohos.permission.ACCESS_DDK_USB\n @return {@link USB_DDK_SUCCESS} the operation is successful.\n         {@link USB_DDK_INVALID_OPERATION} connect usb ddk service failed or internal error.\n         {@link USB_DDK_NO_PERM} permission check failed.\n         {@link USB_DDK_MEMORY_ERROR} memory allocation failed.\n @since 10\n @version 1.0"]
    pub fn OH_Usb_Init() -> i32;
}
extern "C" {
    #[doc = " @brief Releases the DDK.\n\n @permission ohos.permission.ACCESS_DDK_USB\n @since 10\n @version 1.0"]
    pub fn OH_Usb_Release();
}
extern "C" {
    #[doc = " @brief Releases the DDK.\n\n @permission ohos.permission.ACCESS_DDK_USB\n @return {@link USB_DDK_SUCCESS} the operation is successful.\n         {@link USB_DDK_NO_PERM} permission check failed.\n         {@link USB_DDK_INVALID_OPERATION} connect usb ddk service failed.\n @since 18\n @version 1.0"]
    #[cfg(feature = "api-18")]
    pub fn OH_Usb_ReleaseResource() -> i32;
}
extern "C" {
    #[doc = " @brief Obtains the USB device descriptor.\n\n @permission ohos.permission.ACCESS_DDK_USB\n @param deviceId ID of the device whose descriptor is to be obtained.\n @param desc Standard device descriptor defined in the USB protocol.\n @return {@link USB_DDK_SUCCESS} the operation is successful.\n         {@link USB_DDK_NO_PERM} permission check failed.\n         {@link USB_DDK_INVALID_OPERATION} connect usb ddk service failed.\n         {@link USB_DDK_INVALID_PARAMETER} desc is null.\n @since 10\n @version 1.0"]
    pub fn OH_Usb_GetDeviceDescriptor(deviceId: u64, desc: *mut UsbDeviceDescriptor) -> i32;
}
extern "C" {
    #[doc = " @brief Obtains the configuration descriptor. To avoid memory leakage, use <b>OH_Usb_FreeConfigDescriptor</b>\\n\n to release a descriptor after use.\n\n @permission ohos.permission.ACCESS_DDK_USB\n @param deviceId ID of the device whose configuration descriptor is to be obtained.\n @param configIndex Configuration index, which corresponds to <b>bConfigurationValue</b> in the USB protocol.\n @param config Configuration descriptor, which includes the standard configuration descriptor defined in the\\n\n USB protocol and the associated interface descriptor and endpoint descriptor.\n @return {@link USB_DDK_SUCCESS} the operation is successful.\n         {@link USB_DDK_NO_PERM} permission check failed.\n         {@link USB_DDK_INVALID_OPERATION} connect usb ddk service failed.\n         {@link USB_DDK_INVALID_PARAMETER} config is null.\n         {@link USB_DDK_IO_FAILED} data IO exception.\n         {@link USB_DDK_MEMORY_ERROR} memory allocation failed.\n @since 10\n @version 1.0"]
    pub fn OH_Usb_GetConfigDescriptor(
        deviceId: u64,
        configIndex: u8,
        config: *mut *mut UsbDdkConfigDescriptor,
    ) -> i32;
}
extern "C" {
    #[doc = " @brief Releases the configuration descriptor. To avoid memory leakage, use <b>OH_Usb_FreeConfigDescriptor</b>\\n\n to release a descriptor after use.\n\n @permission ohos.permission.ACCESS_DDK_USB\n @param config Configuration descriptor obtained by calling <b>OH_Usb_GetConfigDescriptor</b>.\n @since 10\n @version 1.0"]
    pub fn OH_Usb_FreeConfigDescriptor(config: *mut UsbDdkConfigDescriptor);
}
extern "C" {
    #[doc = " @brief Claims a USB interface.\n\n @permission ohos.permission.ACCESS_DDK_USB\n @param deviceId ID of the device to be operated.\n @param interfaceIndex Interface index, which corresponds to <b>bInterfaceNumber</b> in the USB protocol.\n @param interfaceHandle Interface operation handle. After the interface is claimed successfully, a value will be\\n\n assigned to this parameter.\n @return {@link USB_DDK_SUCCESS} the operation is successful.\n         {@link USB_DDK_NO_PERM} permission check failed.\n         {@link USB_DDK_INVALID_OPERATION} connect usb ddk service failed.\n         {@link USB_DDK_INVALID_PARAMETER} interfaceHandle is null.\n         {@link USB_DDK_MEMORY_ERROR} memory exceeds limit.\n @since 10\n @version 1.0"]
    pub fn OH_Usb_ClaimInterface(
        deviceId: u64,
        interfaceIndex: u8,
        interfaceHandle: *mut u64,
    ) -> i32;
}
extern "C" {
    #[doc = " @brief Releases a USB interface.\n\n @permission ohos.permission.ACCESS_DDK_USB\n @param interfaceHandle Interface operation handle.\n @return {@link USB_DDK_SUCCESS} the operation is successful.\n         {@link USB_DDK_NO_PERM} permission check failed.\n         {@link USB_DDK_INVALID_OPERATION} connect usb ddk service failed.\n         {@link USB_DDK_INVALID_PARAMETER} parameter error.\n @since 10\n @version 1.0"]
    pub fn OH_Usb_ReleaseInterface(interfaceHandle: u64) -> i32;
}
extern "C" {
    #[doc = " @brief Activates the alternate setting of the USB interface.\n\n @permission ohos.permission.ACCESS_DDK_USB\n @param interfaceHandle Interface operation handle.\n @param settingIndex Index of the alternate setting, which corresponds to <b>bAlternateSetting</b>\\n\n in the USB protocol.\n @return {@link USB_DDK_SUCCESS} the operation is successful.\n         {@link USB_DDK_NO_PERM} permission check failed.\n         {@link USB_DDK_INVALID_OPERATION} connect usb ddk service failed.\n         {@link USB_DDK_INVALID_PARAMETER} parameter error.\n @since 10\n @version 1.0"]
    pub fn OH_Usb_SelectInterfaceSetting(interfaceHandle: u64, settingIndex: u8) -> i32;
}
extern "C" {
    #[doc = " @brief Obtains the activated alternate setting of the USB interface.\n\n @permission ohos.permission.ACCESS_DDK_USB\n @param interfaceHandle Interface operation handle.\n @param settingIndex Index of the alternate setting, which corresponds to <b>bAlternateSetting</b>\\n\n in the USB protocol.\n @return {@link USB_DDK_SUCCESS} the operation is successful.\n         {@link USB_DDK_NO_PERM} permission check failed.\n         {@link USB_DDK_INVALID_OPERATION} connect usb ddk service failed.\n         {@link USB_DDK_INVALID_PARAMETER} settingIndex is null.\n @since 10\n @version 1.0"]
    pub fn OH_Usb_GetCurrentInterfaceSetting(interfaceHandle: u64, settingIndex: *mut u8) -> i32;
}
extern "C" {
    #[doc = " @brief Sends a control read transfer request. This API works in a synchronous manner.\n\n @permission ohos.permission.ACCESS_DDK_USB\n @param interfaceHandle Interface operation handle.\n @param setup Request data, which corresponds to <b>Setup Data</b> in the USB protocol.\n @param timeout Timeout duration, in milliseconds.\n @param data Data to be transferred.\n @param dataLen Data length. The return value indicates the length of the actually read data.\n @return {@link USB_DDK_SUCCESS} the operation is successful.\n         {@link USB_DDK_NO_PERM} permission check failed.\n         {@link USB_DDK_INVALID_OPERATION} connect usb ddk service failed.\n         {@link USB_DDK_INVALID_PARAMETER} setup is null or data is null or dataLen is null or dataLen is less than\\n\n         size of the read data.\n         {@link USB_DDK_MEMORY_ERROR} the memory of read data copies failed.\n         {@link USB_DDK_IO_FAILED} data IO exception.\n         {@link USB_DDK_TIMEOUT} interface timeout.\n @since 10\n @version 1.0"]
    pub fn OH_Usb_SendControlReadRequest(
        interfaceHandle: u64,
        setup: *const UsbControlRequestSetup,
        timeout: u32,
        data: *mut u8,
        dataLen: *mut u32,
    ) -> i32;
}
extern "C" {
    #[doc = " @brief Sends a control write transfer request. This API works in a synchronous manner.\n\n @permission ohos.permission.ACCESS_DDK_USB\n @param interfaceHandle Interface operation handle.\n @param setup Request data, which corresponds to <b>Setup Data</b> in the USB protocol.\n @param timeout Timeout duration, in milliseconds.\n @param data Data to be transferred.\n @param dataLen Data length.\n @return {@link USB_DDK_SUCCESS} the operation is successful.\n         {@link USB_DDK_NO_PERM} permission check failed.\n         {@link USB_DDK_INVALID_OPERATION} connect usb ddk service failed.\n         {@link USB_DDK_INVALID_PARAMETER} setup is null or data is null.\n         {@link USB_DDK_MEMORY_ERROR} the memory of read data copies failed.\n         {@link USB_DDK_IO_FAILED} data IO exception.\n         {@link USB_DDK_TIMEOUT} interface timeout.\n @since 10\n @version 1.0"]
    pub fn OH_Usb_SendControlWriteRequest(
        interfaceHandle: u64,
        setup: *const UsbControlRequestSetup,
        timeout: u32,
        data: *const u8,
        dataLen: u32,
    ) -> i32;
}
extern "C" {
    #[doc = " @brief Sends a pipe request. This API works in a synchronous manner. This API applies to interrupt transfer\\n\n and bulk transfer.\n\n @permission ohos.permission.ACCESS_DDK_USB\n @param pipe Pipe used to transfer data.\n @param devMmap Device memory map, which can be obtained by calling <b>OH_Usb_CreateDeviceMemMap</b>.\n @return {@link USB_DDK_SUCCESS} the operation is successful.\n         {@link USB_DDK_NO_PERM} permission check failed.\n         {@link USB_DDK_INVALID_OPERATION} connect usb ddk service failed.\n         {@link USB_DDK_INVALID_PARAMETER} pipe is null or devMmap is null or address of devMmap is null.\n         {@link USB_DDK_MEMORY_ERROR} the memory of read data copies failed.\n         {@link USB_DDK_IO_FAILED} data IO exception.\n         {@link USB_DDK_TIMEOUT} interface timeout.\n @since 10\n @version 1.0"]
    pub fn OH_Usb_SendPipeRequest(
        pipe: *const UsbRequestPipe,
        devMmap: *mut UsbDeviceMemMap,
    ) -> i32;
}
extern "C" {
    #[doc = " @brief Sends a pipe request. This API works in a synchronous manner. This API applies to interrupt transfer\\n\n and bulk transfer.\n\n @permission ohos.permission.ACCESS_DDK_USB\n @param pipe Pipe used to transfer data.\n @param ashmem Shared memory, which can be obtained by calling <b>OH_DDK_CreateAshmem</b>.\n @return {@link USB_DDK_SUCCESS} the operation is successful.\n         {@link USB_DDK_NO_PERM} permission check failed.\n         {@link USB_DDK_INVALID_OPERATION} connect usb ddk service failed.\n         {@link USB_DDK_INVALID_PARAMETER} pipe is null or ashmem is null or address of ashmem is null.\n         {@link USB_DDK_MEMORY_ERROR} the memory of read data copies failed.\n         {@link USB_DDK_IO_FAILED} data IO exception.\n         {@link USB_DDK_TIMEOUT} interface timeout.\n @since 12"]
    pub fn OH_Usb_SendPipeRequestWithAshmem(
        pipe: *const UsbRequestPipe,
        ashmem: *mut DDK_Ashmem,
    ) -> i32;
}
extern "C" {
    #[doc = " @brief Creates a buffer. To avoid resource leakage, destroy a buffer by calling\\n\n <b>OH_Usb_DestroyDeviceMemMap</b> after use.\n\n @permission ohos.permission.ACCESS_DDK_USB\n @param deviceId ID of the device for which the buffer is to be created.\n @param size Buffer size.\n @param devMmap Data memory map, through which the created buffer is returned to the caller.\n @return {@link USB_DDK_SUCCESS} the operation is successful.\n         {@link USB_DDK_NO_PERM} permission check failed.\n         {@link USB_DDK_INVALID_PARAMETER} devMmap is null.\n         {@link USB_DDK_MEMORY_ERROR} mmap failed or alloc memory of devMmap failed.\n @since 10\n @version 1.0"]
    pub fn OH_Usb_CreateDeviceMemMap(
        deviceId: u64,
        size: usize,
        devMmap: *mut *mut UsbDeviceMemMap,
    ) -> i32;
}
extern "C" {
    #[doc = " @brief Destroys a buffer. To avoid resource leakage, destroy a buffer in time after use.\n\n @permission ohos.permission.ACCESS_DDK_USB\n @param devMmap Device memory map created by calling <b>OH_Usb_CreateDeviceMemMap</b>.\n @since 10\n @version 1.0"]
    pub fn OH_Usb_DestroyDeviceMemMap(devMmap: *mut UsbDeviceMemMap);
}
extern "C" {
    #[doc = " @brief Obtain USB devices.\n\n @permission ohos.permission.ACCESS_DDK_USB\n @param devices USB device array.\n @return {@link USB_DDK_SUCCESS} the operation is successful.\n         {@link USB_DDK_NO_PERM} permission check failed.\n         {@link USB_DDK_INVALID_OPERATION} connect usb ddk service failed.\n         {@link USB_DDK_INVALID_PARAMETER} devices is null.\n @since 18"]
    #[cfg(feature = "api-18")]
    pub fn OH_Usb_GetDevices(devices: *mut Usb_DeviceArray) -> i32;
}
extern "C" {
    #[doc = " @brief Creates shared memory. To prevent resource leakage, destroy the shared memory that is not required by\\n\n calling <b>OH_DDK_DestroyAshmem</b>.\n\n @param name Pointer to the shared memory to create.\n @param size Size of the buffer corresponding to the shared memory.\n @param ashmem Pointer to the shared memory created.\n @return {@link DDK_SUCCESS} the operation is successful.\n         {@link DDK_INVALID_PARAMETER} name is NULL, size is 0 or ashmem is NULL.\n         {@link DDK_FAILURE} create the shared memory failed or create structure DDK_Ashmem failed.\n @since 12"]
    pub fn OH_DDK_CreateAshmem(
        name: *const u8,
        size: u32,
        ashmem: *mut *mut DDK_Ashmem,
    ) -> DDK_RetCode;
}
extern "C" {
    #[doc = " @brief Maps the created shared memory to the user space. Unmap the shared memory that is not required by using\\n\n <b>OH_DDK_UnmapAshmem</b>.\n\n @param ashmem Pointer of the shared memory to map.\n @param ashmemMapType Protection permission value of the shared memory.\n @return {@link DDK_SUCCESS} the operation is successful.\n         {@link DDK_NULL_PTR} ashmem is NULL.\n         {@link DDK_FAILURE} the fd of ashmem is invalid.\n         {@link DDK_INVALID_OPERATION} use function MapAshmem failed.\n @since 12"]
    pub fn OH_DDK_MapAshmem(ashmem: *mut DDK_Ashmem, ashmemMapType: u8) -> DDK_RetCode;
}
extern "C" {
    #[doc = " @brief Unmaps shared memory.\n\n @param ashmem Pointer of the shared memory to unmap.\n @return {@link DDK_SUCCESS} the operation is successful.\n         {@link DDK_NULL_PTR} ashmem is NULL.\n         {@link DDK_FAILURE} the fd of ashmem is invalid.\n @since 12"]
    pub fn OH_DDK_UnmapAshmem(ashmem: *mut DDK_Ashmem) -> DDK_RetCode;
}
extern "C" {
    #[doc = " @brief Destroys shared memory.\n\n @param ashmem Pointer of the shared memory to destroy.\n @return {@link DDK_SUCCESS} the operation is successful.\n         {@link DDK_NULL_PTR} ashmem is NULL.\n         {@link DDK_FAILURE} the fd of ashmem is invalid.\n @since 12"]
    pub fn OH_DDK_DestroyAshmem(ashmem: *mut DDK_Ashmem) -> DDK_RetCode;
}
