/* automatically generated by rust-bindgen 0.65.1 */

#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(clippy::missing_safety_doc)]
// bindgen's bitfield accessors transmute/cast between identical types.
#![allow(clippy::useless_transmute)]
#![allow(clippy::unnecessary_cast)]

#[link(name = "purgeable_memory_ndk.z")]
unsafe extern "C" {}

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct PurgMem {
    _unused: [u8; 0],
}
#[doc = " @brief Purgeable mem struct\n\n @since 10\n @version 1.0"]
pub type OH_PurgeableMemory = PurgMem;
#[doc = " @brief: function pointer, it points to a function which is used to build content of a PurgMem obj.\n\n\n @param void *: data ptr, points to start address of a PurgMem obj's content.\n @param size_t Data size of the content.\n @param void *: other private parameters.\n @return: build content result, true means success, while false is fail.\n\n @since 10\n @version 1.0"]
pub type OH_PurgeableMemory_ModifyFunc = ::std::option::Option<
    unsafe extern "C" fn(
        arg1: *mut ::std::os::raw::c_void,
        arg2: usize,
        arg3: *mut ::std::os::raw::c_void,
    ) -> bool,
>;
extern "C" {
    #[doc = " @brief: create a PurgMem obj.\n\n\n @param size Data size of a PurgMem obj's content.\n @param func Function pointer, it is used to recover data when the PurgMem obj's content is purged.\n @param funcPara Parameters used by @func.\n @return: a PurgMem obj.\n\n @since 10\n @version 1.0"]
    pub fn OH_PurgeableMemory_Create(
        size: usize,
        func: OH_PurgeableMemory_ModifyFunc,
        funcPara: *mut ::std::os::raw::c_void,
    ) -> *mut OH_PurgeableMemory;
}
extern "C" {
    #[doc = " @brief: destroy a PurgMem obj.\n\n\n @param purgObj A PurgMem obj to be destroyed.\n @return: true is success, while false is fail. return true if @purgObj is NULL.\n If return true, @purgObj will be set to NULL to avoid Use-After-Free.\n\n @since 10\n @version 1.0"]
    pub fn OH_PurgeableMemory_Destroy(purgObj: *mut OH_PurgeableMemory) -> bool;
}
extern "C" {
    #[doc = " @brief: begin read a PurgMem obj.\n\n\n @param purgObj A PurgMem obj.\n @return: return true if @purgObj's content is present.\n          If content is purged(no present), system will recover its data,\n          return false if content is purged and recovered failed.\n          While return true if content recover success.\n OS cannot reclaim the memory of @purgObj's content when this\n function return true, until PurgMemEndRead() is called.\n\n @since 10\n @version 1.0"]
    pub fn OH_PurgeableMemory_BeginRead(purgObj: *mut OH_PurgeableMemory) -> bool;
}
extern "C" {
    #[doc = " @brief: end read a PurgMem obj.\n\n\n @param purgObj A PurgMem obj.\n OS may reclaim the memory of @purgObj's content\n at a later time when this function returns.\n\n @since 10\n @version 1.0"]
    pub fn OH_PurgeableMemory_EndRead(purgObj: *mut OH_PurgeableMemory);
}
extern "C" {
    #[doc = " @brief: begin write a PurgMem obj.\n\n\n @param purgObj A PurgMem obj.\n @return: return true if @purgObj's content is present.\n          if content is purged(no present), system will recover its data,\n          return false if content is purged and recovered failed.\n          While return true if content is successfully recovered.\n OS cannot reclaim the memory of @purgObj's content when this\n function return true, until PurgMemEndWrite() is called.\n\n @since 10\n @version 1.0"]
    pub fn OH_PurgeableMemory_BeginWrite(purgObj: *mut OH_PurgeableMemory) -> bool;
}
extern "C" {
    #[doc = " @brief: end write a PurgMem obj.\n\n\n @param purgObj A PurgMem obj.\n OS may reclaim the memory of @purgObj's content\n at a later time when this function returns.\n\n @since 10\n @version 1.0"]
    pub fn OH_PurgeableMemory_EndWrite(purgObj: *mut OH_PurgeableMemory);
}
extern "C" {
    #[doc = " @brief: get content ptr of a PurgMem obj.\n\n\n @param purgObj A PurgMem obj.\n @return: return start address of a PurgMem obj's content.\n          Return NULL if @purgObj is NULL.\n This function should be protect by PurgMemBeginRead()/PurgMemEndRead()\n or PurgMemBeginWrite()/PurgMemEndWrite()\n\n @since 10\n @version 1.0"]
    pub fn OH_PurgeableMemory_GetContent(
        purgObj: *mut OH_PurgeableMemory,
    ) -> *mut ::std::os::raw::c_void;
}
extern "C" {
    #[doc = " @brief: get content size of a PurgMem obj.\n\n\n @param purgObj A PurgMem obj.\n @return: return content size of @purgObj.\n          Return 0 if @purgObj is NULL.\n\n @since 10\n @version 1.0"]
    pub fn OH_PurgeableMemory_ContentSize(purgObj: *mut OH_PurgeableMemory) -> usize;
}
extern "C" {
    #[doc = " @brief: append a modify to a PurgMem obj.\n\n\n @param purgObj A PurgMem obj.\n @param func Function pointer, it will modify content of @PurgMem.\n @param funcPara Parameters used by @func.\n @return:  append result, true is success, while false is fail.\n\n @since 10\n @version 1.0"]
    pub fn OH_PurgeableMemory_AppendModify(
        purgObj: *mut OH_PurgeableMemory,
        func: OH_PurgeableMemory_ModifyFunc,
        funcPara: *mut ::std::os::raw::c_void,
    ) -> bool;
}
