/* automatically generated by rust-bindgen 0.65.1 */

#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(clippy::missing_safety_doc)]
// bindgen's bitfield accessors transmute/cast between identical types.
#![allow(clippy::useless_transmute)]
#![allow(clippy::unnecessary_cast)]

#[link(name = "hiappevent_ndk.z")]
unsafe extern "C" {}

pub const DISABLE: &[u8; 8usize] = b"disable\0";
pub const MAX_STORAGE: &[u8; 12usize] = b"max_storage\0";
pub const EVENT_USER_LOGIN: &[u8; 22usize] = b"hiappevent.user_login\0";
pub const EVENT_USER_LOGOUT: &[u8; 23usize] = b"hiappevent.user_logout\0";
pub const EVENT_DISTRIBUTED_SERVICE_START: &[u8; 37usize] =
    b"hiappevent.distributed_service_start\0";
pub const EVENT_APP_CRASH: &[u8; 10usize] = b"APP_CRASH\0";
pub const EVENT_APP_FREEZE: &[u8; 11usize] = b"APP_FREEZE\0";
pub const EVENT_APP_LAUNCH: &[u8; 11usize] = b"APP_LAUNCH\0";
pub const EVENT_SCROLL_JANK: &[u8; 12usize] = b"SCROLL_JANK\0";
pub const EVENT_CPU_USAGE_HIGH: &[u8; 15usize] = b"CPU_USAGE_HIGH\0";
pub const EVENT_BATTERY_USAGE: &[u8; 14usize] = b"BATTERY_USAGE\0";
pub const EVENT_RESOURCE_OVERLIMIT: &[u8; 19usize] = b"RESOURCE_OVERLIMIT\0";
pub const EVENT_ADDRESS_SANITIZER: &[u8; 18usize] = b"ADDRESS_SANITIZER\0";
pub const EVENT_MAIN_THREAD_JANK: &[u8; 17usize] = b"MAIN_THREAD_JANK\0";
pub const EVENT_MAIN_THREAD_JANK_V2: &[u8; 20usize] = b"MAIN_THREAD_JANK_V2\0";
pub const EVENT_APP_HICOLLIE: &[u8; 13usize] = b"APP_HICOLLIE\0";
pub const EVENT_APP_KILLED: &[u8; 11usize] = b"APP_KILLED\0";
pub const EVENT_AUDIO_JANK_FRAME: &[u8; 17usize] = b"AUDIO_JANK_FRAME\0";
pub const DOMAIN_OS: &[u8; 3usize] = b"OS\0";
pub const PARAM_USER_ID: &[u8; 8usize] = b"user_id\0";
pub const PARAM_DISTRIBUTED_SERVICE_NAME: &[u8; 8usize] = b"ds_name\0";
pub const PARAM_DISTRIBUTED_SERVICE_INSTANCE_ID: &[u8; 15usize] = b"ds_instance_id\0";
pub const MAIN_THREAD_JANK_PARAM_LOG_TYPE: &[u8; 9usize] = b"log_type\0";
pub const MAIN_THREAD_JANK_PARAM_SAMPLE_INTERVAL: &[u8; 16usize] = b"sample_interval\0";
pub const MAIN_THREAD_JANK_PARAM_IGNORE_STARTUP_TIME: &[u8; 20usize] = b"ignore_startup_time\0";
pub const MAIN_THREAD_JANK_PARAM_SAMPLE_COUNT: &[u8; 13usize] = b"sample_count\0";
pub const MAIN_THREAD_JANK_PARAM_REPORT_TIMES_PER_APP: &[u8; 21usize] = b"report_times_per_app\0";
pub const MAIN_THREAD_JANK_PARAM_AUTO_STOP_SAMPLING: &[u8; 19usize] = b"auto_stop_sampling\0";
pub const OH_APP_CRASH_PARAM_EXTEND_PC_LR_PRINTING: &[u8; 22usize] = b"extend_pc_lr_printing\0";
pub const OH_APP_CRASH_PARAM_LOG_FILE_CUTOFF_SZ_BYTES: &[u8; 25usize] =
    b"log_file_cutoff_sz_bytes\0";
pub const OH_APP_CRASH_PARAM_SIMPLIFY_VMA_PRINTING: &[u8; 22usize] = b"simplify_vma_printing\0";
pub const OH_APP_CRASH_PARAM_MERGE_CPPCRASH_APP_LOG: &[u8; 23usize] = b"merge_cppcrash_app_log\0";
#[doc = " @error The operation is successful."]
#[cfg(feature = "api-15")]
pub const HiAppEvent_ErrorCode_HIAPPEVENT_SUCCESS: HiAppEvent_ErrorCode = 0;
#[doc = " @error Invalid param value length\n @since 18"]
#[cfg(feature = "api-18")]
pub const HiAppEvent_ErrorCode_HIAPPEVENT_INVALID_PARAM_VALUE_LENGTH: HiAppEvent_ErrorCode = 4;
#[doc = " @error Processor is null\n @since 18"]
#[cfg(feature = "api-18")]
pub const HiAppEvent_ErrorCode_HIAPPEVENT_PROCESSOR_IS_NULL: HiAppEvent_ErrorCode = -7;
#[doc = " @error Processor not found\n @since 18"]
#[cfg(feature = "api-18")]
pub const HiAppEvent_ErrorCode_HIAPPEVENT_PROCESSOR_NOT_FOUND: HiAppEvent_ErrorCode = -8;
#[doc = " @error Invalid param value"]
#[cfg(feature = "api-15")]
pub const HiAppEvent_ErrorCode_HIAPPEVENT_INVALID_PARAM_VALUE: HiAppEvent_ErrorCode = -9;
#[doc = " @error event config is null"]
#[cfg(feature = "api-15")]
pub const HiAppEvent_ErrorCode_HIAPPEVENT_EVENT_CONFIG_IS_NULL: HiAppEvent_ErrorCode = -10;
#[doc = " @error Operate failed\n @since 18"]
#[cfg(feature = "api-18")]
pub const HiAppEvent_ErrorCode_HIAPPEVENT_OPERATE_FAILED: HiAppEvent_ErrorCode = -100;
#[doc = " @error Invalid uid\n @since 18"]
#[cfg(feature = "api-18")]
pub const HiAppEvent_ErrorCode_HIAPPEVENT_INVALID_UID: HiAppEvent_ErrorCode = -200;
#[doc = " @brief Defines error code\n\n @since 15"]
#[cfg(feature = "api-15")]
pub type HiAppEvent_ErrorCode = i32;
pub const EventType_FAULT: EventType = 1;
pub const EventType_STATISTIC: EventType = 2;
pub const EventType_SECURITY: EventType = 3;
pub const EventType_BEHAVIOR: EventType = 4;
#[doc = " @brief Event types.\n\n You are advised to select event types based on their respective usage scenarios.\n\n @since 8\n @version 1.0"]
pub type EventType = u32;
#[doc = " @brief The HiAppEvent_AppEventInfo structure is used to represent event information in an application, including\n the event's domain, name, type, and parameters.\n\n @since 12\n @version 1.0"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct HiAppEvent_AppEventInfo {
    pub domain: *const ::std::os::raw::c_char,
    pub name: *const ::std::os::raw::c_char,
    pub type_: EventType,
    pub params: *const ::std::os::raw::c_char,
}
#[doc = " @brief The HiAppEvent_AppEventGroup structure represents a group of events in an application. It contains the name\n of the event group, an array of HiAppEvent_AppEventInfo structures representing individual events grouped by the\n name, and the length of the event array.\n\n @syscap SystemCapability.HiviewDFX.HiAppEvent\n @since 12\n @version 1.0"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct HiAppEvent_AppEventGroup {
    pub name: *const ::std::os::raw::c_char,
    pub appEventInfos: *const HiAppEvent_AppEventInfo,
    pub infoLen: u32,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ParamListNode {
    _unused: [u8; 0],
}
#[doc = " @brief Event param list node.\n\n @since 8\n @version 1.0"]
pub type ParamList = *mut ParamListNode;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct HiAppEvent_Watcher {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct HiAppEvent_Processor {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct HiAppEvent_Config {
    _unused: [u8; 0],
}
#[doc = " @brief The OH_HiAppEvent_OnReceive function acts as the callback function for the HiAppEvent_Watcher. It is called\n when an event occurs.\n\n @param domain The domain of the event.\n @param appEventGroups The event group by the domain.\n @param groupLen The length of appEventGroups array.\n @since 12\n @version 1.0"]
pub type OH_HiAppEvent_OnReceive = ::std::option::Option<
    unsafe extern "C" fn(
        domain: *const ::std::os::raw::c_char,
        appEventGroups: *const HiAppEvent_AppEventGroup,
        groupLen: u32,
    ),
>;
#[doc = " @brief Called when watcher receive the event meet the condition.\n\n @param row The row of events received by watcher.\n @param size The size of events received by watcher.\n @since 12\n @version 1.0"]
pub type OH_HiAppEvent_OnTrigger = ::std::option::Option<
    unsafe extern "C" fn(row: ::std::os::raw::c_int, size: ::std::os::raw::c_int),
>;
#[doc = " @brief Called when watcher take the events.\n\n @param events The event json string array.\n @param eventLen The length of events array.\n @since 12\n @version 1.0"]
pub type OH_HiAppEvent_OnTake = ::std::option::Option<
    unsafe extern "C" fn(events: *const *const ::std::os::raw::c_char, eventLen: u32),
>;
extern "C" {
    #[doc = " @brief Create a pointer to the ParamList.\n\n @return Pointer to the ParamList.\n @since 8\n @version 1.0"]
    pub fn OH_HiAppEvent_CreateParamList() -> ParamList;
}
extern "C" {
    #[doc = " @brief Destroy a pointer to the ParamList.\n\n @param list Event param list.\n @since 8\n @version 1.0"]
    pub fn OH_HiAppEvent_DestroyParamList(list: ParamList);
}
extern "C" {
    #[doc = " @brief Add bool param to the ParamList.\n\n @param list The ParamList of params to be added.\n @param name The name of the param to be added.\n @param boolean The bool value of the param to be added.\n @return ParamList after the param is added.\n @since 8\n @version 1.0"]
    pub fn OH_HiAppEvent_AddBoolParam(
        list: ParamList,
        name: *const ::std::os::raw::c_char,
        boolean: bool,
    ) -> ParamList;
}
extern "C" {
    #[doc = " @brief Add bool array param to the ParamList.\n\n @param list The ParamList of params to be added.\n @param name The name of the param to be added.\n @param booleans The bool array value of the param to be added.\n @param arrSize The array size of the param to be added.\n @return ParamList after the param is added.\n @since 8\n @version 1.0"]
    pub fn OH_HiAppEvent_AddBoolArrayParam(
        list: ParamList,
        name: *const ::std::os::raw::c_char,
        booleans: *const bool,
        arrSize: ::std::os::raw::c_int,
    ) -> ParamList;
}
extern "C" {
    #[doc = " @brief Add int8_t param to the ParamList.\n\n @param list The ParamList of params to be added.\n @param name The name of the param to be added.\n @param num The int8_t value of the param to be added.\n @return ParamList after the param is added.\n @since 8\n @version 1.0"]
    pub fn OH_HiAppEvent_AddInt8Param(
        list: ParamList,
        name: *const ::std::os::raw::c_char,
        num: i8,
    ) -> ParamList;
}
extern "C" {
    #[doc = " @brief Add int8_t array param to the ParamList.\n\n @param list The ParamList of params to be added.\n @param name The name of the param to be added.\n @param nums The int8_t array value of the param to be added.\n @param arrSize The array size of the param to be added.\n @return ParamList after the param is added.\n @since 8\n @version 1.0"]
    pub fn OH_HiAppEvent_AddInt8ArrayParam(
        list: ParamList,
        name: *const ::std::os::raw::c_char,
        nums: *const i8,
        arrSize: ::std::os::raw::c_int,
    ) -> ParamList;
}
extern "C" {
    #[doc = " @brief Add int16_t param to the ParamList.\n\n @param list The ParamList of params to be added.\n @param name The name of the param to be added.\n @param num The int16_t value of the param to be added.\n @return ParamList after the param is added.\n @since 8\n @version 1.0"]
    pub fn OH_HiAppEvent_AddInt16Param(
        list: ParamList,
        name: *const ::std::os::raw::c_char,
        num: i16,
    ) -> ParamList;
}
extern "C" {
    #[doc = " @brief Add int16_t array param to the ParamList.\n\n @param list The ParamList of params to be added.\n @param name The name of the param to be added.\n @param nums The int16_t array value of the param to be added.\n @param arrSize The array size of the param to be added.\n @return ParamList after the param is added.\n @since 8\n @version 1.0"]
    pub fn OH_HiAppEvent_AddInt16ArrayParam(
        list: ParamList,
        name: *const ::std::os::raw::c_char,
        nums: *const i16,
        arrSize: ::std::os::raw::c_int,
    ) -> ParamList;
}
extern "C" {
    #[doc = " @brief Add int32_t param to the ParamList.\n\n @param list The ParamList of params to be added.\n @param name The name of the param to be added.\n @param num The int32_t value of the param to be added.\n @return ParamList after the param is added.\n @since 8\n @version 1.0"]
    pub fn OH_HiAppEvent_AddInt32Param(
        list: ParamList,
        name: *const ::std::os::raw::c_char,
        num: i32,
    ) -> ParamList;
}
extern "C" {
    #[doc = " @brief Add int32_t array param to the ParamList.\n\n @param list The ParamList of params to be added.\n @param name The name of the param to be added.\n @param nums The int32_t array value of the param to be added.\n @param arrSize The array size of the param to be added.\n @return ParamList after the param is added.\n @since 8\n @version 1.0"]
    pub fn OH_HiAppEvent_AddInt32ArrayParam(
        list: ParamList,
        name: *const ::std::os::raw::c_char,
        nums: *const i32,
        arrSize: ::std::os::raw::c_int,
    ) -> ParamList;
}
extern "C" {
    #[doc = " @brief Add int64_t param to the ParamList.\n\n @param list The ParamList of params to be added.\n @param name The name of the param to be added.\n @param num The int64_t value of the param to be added.\n @return ParamList after the param is added.\n @since 8\n @version 1.0"]
    pub fn OH_HiAppEvent_AddInt64Param(
        list: ParamList,
        name: *const ::std::os::raw::c_char,
        num: i64,
    ) -> ParamList;
}
extern "C" {
    #[doc = " @brief Add int64_t array param to the ParamList.\n\n @param list The ParamList of params to be added.\n @param name The name of the param to be added.\n @param nums The int64_t array value of the param to be added.\n @param arrSize The array size of the param to be added.\n @return ParamList after the param is added.\n @since 8\n @version 1.0"]
    pub fn OH_HiAppEvent_AddInt64ArrayParam(
        list: ParamList,
        name: *const ::std::os::raw::c_char,
        nums: *const i64,
        arrSize: ::std::os::raw::c_int,
    ) -> ParamList;
}
extern "C" {
    #[doc = " @brief Add float param to the ParamList.\n\n @param list The ParamList of params to be added.\n @param name The name of the param to be added.\n @param num The float value of the param to be added.\n @return ParamList after the param is added.\n @since 8\n @version 1.0"]
    pub fn OH_HiAppEvent_AddFloatParam(
        list: ParamList,
        name: *const ::std::os::raw::c_char,
        num: f32,
    ) -> ParamList;
}
extern "C" {
    #[doc = " @brief Add float array param to the ParamList.\n\n @param list The ParamList of params to be added.\n @param name The name of the param to be added.\n @param nums The float array value of the param to be added.\n @param arrSize The array size of the param to be added.\n @return ParamList after the param is added.\n @since 8\n @version 1.0"]
    pub fn OH_HiAppEvent_AddFloatArrayParam(
        list: ParamList,
        name: *const ::std::os::raw::c_char,
        nums: *const f32,
        arrSize: ::std::os::raw::c_int,
    ) -> ParamList;
}
extern "C" {
    #[doc = " @brief Add double param to the ParamList.\n\n @param list The ParamList of params to be added.\n @param name The name of the param to be added.\n @param num The double value of the param to be added.\n @return ParamList after the param is added.\n @since 8\n @version 1.0"]
    pub fn OH_HiAppEvent_AddDoubleParam(
        list: ParamList,
        name: *const ::std::os::raw::c_char,
        num: f64,
    ) -> ParamList;
}
extern "C" {
    #[doc = " @brief Add double array param to the ParamList.\n\n @param list The ParamList of params to be added.\n @param name The name of the param to be added.\n @param nums The double array value of the param to be added.\n @param arrSize The array size of the param to be added.\n @return ParamList after the param is added.\n @since 8\n @version 1.0"]
    pub fn OH_HiAppEvent_AddDoubleArrayParam(
        list: ParamList,
        name: *const ::std::os::raw::c_char,
        nums: *const f64,
        arrSize: ::std::os::raw::c_int,
    ) -> ParamList;
}
extern "C" {
    #[doc = " @brief Add string param to the ParamList.\n\n @param list The ParamList of params to be added.\n @param name The name of the param to be added.\n @param str The string value of the param to be added.\n @return ParamList after the param is added.\n @since 8\n @version 1.0"]
    pub fn OH_HiAppEvent_AddStringParam(
        list: ParamList,
        name: *const ::std::os::raw::c_char,
        str_: *const ::std::os::raw::c_char,
    ) -> ParamList;
}
extern "C" {
    #[doc = " @brief Add string array param to the ParamList.\n\n @param list The ParamList of params to be added.\n @param name The name of the param to be added.\n @param strs The string array value of the param to be added.\n @param arrSize The array size of the param to be added.\n @return ParamList after the param is added.\n @since 8\n @version 1.0"]
    pub fn OH_HiAppEvent_AddStringArrayParam(
        list: ParamList,
        name: *const ::std::os::raw::c_char,
        strs: *const *const ::std::os::raw::c_char,
        arrSize: ::std::os::raw::c_int,
    ) -> ParamList;
}
extern "C" {
    #[doc = " @brief Implements logging of application events whose parameters are of the list type.\n\n Before logging an application event, this API will first verify parameters of this event.\n If the verification is successful, the API will write the event to the event file.\n\n @param domain Indicates the event domain. You can customize the event domain as needed.\n @param name Indicates the event name. You can customize the event name as needed.\n @param type Indicates the event type, which is defined in {@link EventType}.\n @param list Indicates a linked list of event parameters, each of which is comprised of the parameter name and\n parameter value.\n @return Returns 0 if the event parameter verification is successful, and the event will be written to\n the event file; returns a positive integer if invalid parameters are present in the event, and\n the event will be written to the event file after the invalid parameters are ignored; returns a\n negative integer if the event parameter verification fails, and the event will not be written to the event file.\n         {@code 0} Parameters verification is successful.\n         {@code -1} Invalid event name.\n         {@code -4} Invalid event domain.\n         {@code -99} Function disabled.\n         {@code 1} Invalid event parameter name.\n         {@code 4} Invalid string length of the event parameter.\n         {@code 5} Invalid number of event parameters.\n         {@code 6} Invalid array length of the event parameter.\n         {@code 8} Duplicate parameter.\n @since 8\n @version 1.0"]
    pub fn OH_HiAppEvent_Write(
        domain: *const ::std::os::raw::c_char,
        name: *const ::std::os::raw::c_char,
        type_: EventType,
        list: ParamList,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    #[doc = " @brief Implements the configuration function of application events logging.\n\n Application event logging configuration interface, which is used to configure event logging switch,\n event file directory storage quota size and other functions.\n\n @param name Configuration item name.\n @param value Configuration item value.\n @return Returns true if configuration successful; returns false if configuration failed.\n @since 8\n @version 1.0"]
    pub fn OH_HiAppEvent_Configure(
        name: *const ::std::os::raw::c_char,
        value: *const ::std::os::raw::c_char,
    ) -> bool;
}
extern "C" {
    #[doc = " @brief Create a HiAppEvent_Watcher handler pointer to set the property.\n\n @param name The name of the watcher.\n @return Returns a pointer to the HiAppEvent_Watcher instance.\n @since 12\n @version 1.0"]
    pub fn OH_HiAppEvent_CreateWatcher(
        name: *const ::std::os::raw::c_char,
    ) -> *mut HiAppEvent_Watcher;
}
extern "C" {
    #[doc = " @brief Destroy the specified HiAppEvent_Watcher handle resource.\n\n @param watcher The pointer to the HiAppEvent_Watcher instance.\n @since 12\n @version 1.0"]
    pub fn OH_HiAppEvent_DestroyWatcher(watcher: *mut HiAppEvent_Watcher);
}
extern "C" {
    #[doc = " @brief The interface to set trigger conditions for the watcher. Three trigger conditions can be set through this\n interface and any of the condition which is set over than 0 met, the onTrigger callback set through\n OH_HiAppEvent_SetWatcherOnTrigger will be invoked.\n\n @param watcher The pointer to the HiAppEvent_Watcher instance.\n @param row The row of write events that trigger the onTrigger callback.\n @param size The size of write events that trigger the onTrigger callback.\n @param timeOut The interval for trigger the onTrigger callback.\n @return Returns 0 if set TriggerCondition is successful, and returns a\n negative integer if set fail.\n         {@code 0} Success.\n         {@code -5} The watcher is nullptr.\n @since 12\n @version 1.0"]
    pub fn OH_HiAppEvent_SetTriggerCondition(
        watcher: *mut HiAppEvent_Watcher,
        row: ::std::os::raw::c_int,
        size: ::std::os::raw::c_int,
        timeOut: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    #[doc = " @brief The interface to set the AppEventFilter which defines the kind of app events will be received by  the watcher.\n\n @param watcher The pointer to the HiAppEvent_Watcher instance.\n @param domain The name of the event domain to be monitored by the watcher.\n @param eventTypes The types of the events to be monitored by the watcher.0x08 means BEHAVIOR,0x04 means\n SECURITY, 0x02 means STATISTIC,0x01 means FAULT, 0xff and 0x00 means all.\n @param names The names of the events to be monitored by the watcher.\n @param namesLen The length of names array.\n @return Returns 0 if set AppEventFilter is successful, and returns a\n negative integer if set fail.\n         {@code 0} Success.\n         {@code -1} Invalid event name.\n         {@code -4} Invalid event domain.\n         {@code -5} The watcher is nullptr.\n @since 12\n @version 1.0"]
    pub fn OH_HiAppEvent_SetAppEventFilter(
        watcher: *mut HiAppEvent_Watcher,
        domain: *const ::std::os::raw::c_char,
        eventTypes: u8,
        names: *const *const ::std::os::raw::c_char,
        namesLen: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    #[doc = " @brief The interface to set onTrigger callback for watcher. If the OnReceive callback is not be set or has been set\n to nullptr, the app events received by the watcher will be saved. When the new saved appEvents met the conditions set\n by OH_HiAppEvent_SetTriggerCondition, the onTrigger callback will be invoked.\n\n @param watcher The pointer to the HiAppEvent_Watcher instance.\n @param onTrigger The callback of the watcher.\n @return Returns 0 if set OnTrigger is successful, and returns a\n negative integer if set fail.\n         {@code 0} Success.\n         {@code -5} The watcher is nullptr.\n @since 12\n @version 1.0"]
    pub fn OH_HiAppEvent_SetWatcherOnTrigger(
        watcher: *mut HiAppEvent_Watcher,
        onTrigger: OH_HiAppEvent_OnTrigger,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    #[doc = " @brief The interface to set onReceive callback for watcher. When the watcher received an app event, the onReceive\n callback set will be invoked.\n\n @param watcher The pointer to the HiAppEvent_Watcher instance.\n @param onReceive The callback of the watcher.\n @return Returns 0 if set OnReceive is successful, and returns a\n negative integer if set fail.\n         {@code 0} Success.\n         {@code -5} The watcher is nullptr.\n @since 12\n @version 1.0"]
    pub fn OH_HiAppEvent_SetWatcherOnReceive(
        watcher: *mut HiAppEvent_Watcher,
        onReceive: OH_HiAppEvent_OnReceive,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    #[doc = " @brief The interface to take saved events data for the watcher.\n\n @param watcher The pointer to the HiAppEvent_Watcher instance.\n @param eventNum The num of events to take.\n @param onTake The callback of the watcher.\n @return Returns 0 if take events is successful, and returns a\n negative integer if take fail.\n         {@code 0} Success.\n         {@code -5} The watcher is nullptr.\n         {@code -6} This interface must be called after OH_HiAppEvent_AddWatcher.\n @since 12\n @version 1.0"]
    pub fn OH_HiAppEvent_TakeWatcherData(
        watcher: *mut HiAppEvent_Watcher,
        eventNum: u32,
        onTake: OH_HiAppEvent_OnTake,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    #[doc = " @brief The interface to add the watcher. The watcher will start receiving app events after it is added.\n\n @param watcher The pointer to the HiAppEvent_Watcher instance which receive the event.\n @return Returns 0 if add watcher is successful, and returns a\n negative integer if add fail.\n         {@code 0} Success.\n         {@code -5} The watcher is nullptr.\n @since 12\n @version 1.0"]
    pub fn OH_HiAppEvent_AddWatcher(watcher: *mut HiAppEvent_Watcher) -> ::std::os::raw::c_int;
}
extern "C" {
    #[doc = " @brief The interface to remove the watcher. The watcher will stop receiving app events after it is removed.\n\n @param watcher The pointer to the HiAppEvent_Watcher instance.\n @return Returns 0 if remove watcher is successful, and returns a\n negative integer if remove fail.\n         {@code 0} Success.\n         {@code -5} The watcher is nullptr.\n         {@code -6} This interface must be called after OH_HiAppEvent_AddWatcher.\n @since 12\n @version 1.0"]
    pub fn OH_HiAppEvent_RemoveWatcher(watcher: *mut HiAppEvent_Watcher) -> ::std::os::raw::c_int;
}
extern "C" {
    #[doc = " @brief Clear all local saved event data of the application.\n\n @since 12\n @version 1.0"]
    pub fn OH_HiAppEvent_ClearData();
}
extern "C" {
    #[doc = " @brief Create a HiAppEvent_Processor handler pointer to set the property.\n\n @param name The name of the processor.\n @return Returns a pointer to the HiAppEvent_Processor instance.\n @since 18"]
    #[cfg(feature = "api-18")]
    pub fn OH_HiAppEvent_CreateProcessor(
        name: *const ::std::os::raw::c_char,
    ) -> *mut HiAppEvent_Processor;
}
extern "C" {
    #[doc = " @brief The interface to set route for processor.\n\n @param processor The pointer to the HiAppEvent_Processor instance.\n @param appId The appid of the processor.\n @param routeInfo The server location information.\n @return set result.\n         {@link HIAPPEVENT_SUCCESS} The operation is successful.\n         {@link HIAPPEVENT_PROCESSOR_IS_NULL} The processor is nullptr.\n         {@link HIAPPEVENT_INVALID_PARAM_VALUE} Invalid Param value.\n         {@link HIAPPEVENT_INVALID_UID} Invalid uid.\n         {@link HIAPPEVENT_INVALID_PARAM_VALUE_LENGTH} Invalid param value length.\n @since 18"]
    #[cfg(feature = "api-18")]
    pub fn OH_HiAppEvent_SetReportRoute(
        processor: *mut HiAppEvent_Processor,
        appId: *const ::std::os::raw::c_char,
        routeInfo: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    #[doc = " @brief The interface to set policy for processor.\n\n @param processor The pointer to the HiAppEvent_Processor instance.\n @param periodReport The time interval to report.\n @param batchReport The threthold to report.\n @param onStartReport The strategy to report.\n @param onBackgroundReport The strategy to report.\n @return set result.\n         {@link HIAPPEVENT_SUCCESS} The operation is successful.\n         {@link HIAPPEVENT_PROCESSOR_IS_NULL} The processor is nullptr.\n         {@link HIAPPEVENT_INVALID_PARAM_VALUE} Invalid Param value.\n         {@link HIAPPEVENT_INVALID_UID} Invalid uid.\n @since 18"]
    #[cfg(feature = "api-18")]
    pub fn OH_HiAppEvent_SetReportPolicy(
        processor: *mut HiAppEvent_Processor,
        periodReport: ::std::os::raw::c_int,
        batchReport: ::std::os::raw::c_int,
        onStartReport: bool,
        onBackgroundReport: bool,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    #[doc = " @brief The interface to set report event for processor.\n\n @param processor The pointer to the HiAppEvent_Processor instance.\n @param domain The event domain to report.\n @param name The event name to report.\n @param isRealTime The strategy to report.\n @return set result.\n         {@link HIAPPEVENT_SUCCESS} The operation is successful.\n         {@link HIAPPEVENT_PROCESSOR_IS_NULL} The processor is nullptr.\n         {@link HIAPPEVENT_INVALID_PARAM_VALUE} Invalid Param value.\n         {@link HIAPPEVENT_INVALID_UID} Invalid uid.\n @since 18"]
    #[cfg(feature = "api-18")]
    pub fn OH_HiAppEvent_SetReportEvent(
        processor: *mut HiAppEvent_Processor,
        domain: *const ::std::os::raw::c_char,
        name: *const ::std::os::raw::c_char,
        isRealTime: bool,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    #[doc = " @brief The interface to set config for processor.\n\n @param processor The pointer to the HiAppEvent_Processor instance.\n @param key The custom key of processor.\n @param value The custom value of processor.\n @return set result.\n         {@link HIAPPEVENT_SUCCESS} The operation is successful.\n         {@link HIAPPEVENT_PROCESSOR_IS_NULL} The processor is nullptr.\n         {@link HIAPPEVENT_INVALID_PARAM_VALUE} Invalid Param value.\n         {@link HIAPPEVENT_INVALID_UID} Invalid uid.\n         {@link HIAPPEVENT_INVALID_PARAM_VALUE_LENGTH} Invalid param value length.\n @since 18"]
    #[cfg(feature = "api-18")]
    pub fn OH_HiAppEvent_SetCustomConfig(
        processor: *mut HiAppEvent_Processor,
        key: *const ::std::os::raw::c_char,
        value: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    #[doc = " @brief The interface to set configId for processor.\n\n @param processor The pointer to the HiAppEvent_Processor instance.\n @param configId The configId of processor.\n @return set result.\n         {@link HIAPPEVENT_SUCCESS} The operation is successful.\n         {@link HIAPPEVENT_PROCESSOR_IS_NULL} The processor is nullptr.\n         {@link HIAPPEVENT_INVALID_PARAM_VALUE} Invalid Param value.\n         {@link HIAPPEVENT_INVALID_UID} Invalid uid.\n @since 18"]
    #[cfg(feature = "api-18")]
    pub fn OH_HiAppEvent_SetConfigId(
        processor: *mut HiAppEvent_Processor,
        configId: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    #[doc = " @brief The interface to set config Name for processor.\n\n @param processor The pointer to the HiAppEvent_Processor instance.\n @param configName The configName of processor.\n @return set result.\n         {@link HIAPPEVENT_SUCCESS} The operation is successful.\n         {@link HIAPPEVENT_PROCESSOR_IS_NULL} The processor is nullptr.\n         {@link HIAPPEVENT_INVALID_PARAM_VALUE} Invalid Param value.\n         {@link HIAPPEVENT_INVALID_UID} Invalid uid.\n         {@link HIAPPEVENT_INVALID_PARAM_VALUE_LENGTH} Invalid param value length.\n @since 20"]
    #[cfg(feature = "api-20")]
    pub fn OH_HiAppEvent_SetConfigName(
        processor: *mut HiAppEvent_Processor,
        configName: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    #[doc = " @brief The interface to set user info for processor.\n\n @param processor The pointer to the HiAppEvent_Processor instance.\n @param userIdNames The userIdNames of processor.\n @param size The size of userIdNames array.\n @return set result.\n         {@link HIAPPEVENT_SUCCESS} The operation is successful.\n         {@link HIAPPEVENT_PROCESSOR_IS_NULL} The processor is nullptr.\n         {@link HIAPPEVENT_INVALID_PARAM_VALUE} Invalid Param value.\n         {@link HIAPPEVENT_INVALID_UID} Invalid uid.\n         {@link HIAPPEVENT_INVALID_PARAM_VALUE_LENGTH} Invalid param value length.\n @since 18"]
    #[cfg(feature = "api-18")]
    pub fn OH_HiAppEvent_SetReportUserId(
        processor: *mut HiAppEvent_Processor,
        userIdNames: *const *const ::std::os::raw::c_char,
        size: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    #[doc = " @brief The interface to set user property for processor.\n\n @param processor The pointer to the HiAppEvent_Processor instance.\n @param userPropertyNames The userPropertyNames of processor.\n @param size The size of userPropertyNames array.\n @return set result.\n         {@link HIAPPEVENT_SUCCESS} The operation is successful.\n         {@link HIAPPEVENT_PROCESSOR_IS_NULL} The processor is nullptr.\n         {@link HIAPPEVENT_INVALID_PARAM_VALUE} Invalid Param value.\n         {@link HIAPPEVENT_INVALID_UID} Invalid uid.\n         {@link HIAPPEVENT_INVALID_PARAM_VALUE_LENGTH} Invalid param value length.\n @since 18"]
    #[cfg(feature = "api-18")]
    pub fn OH_HiAppEvent_SetReportUserProperty(
        processor: *mut HiAppEvent_Processor,
        userPropertyNames: *const *const ::std::os::raw::c_char,
        size: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    #[doc = " @brief The interface to add processor.\n\n @param processor The pointer to the HiAppEvent_Processor instance.\n @return process id if set is successful.\n         {@link HIAPPEVENT_PROCESSOR_IS_NULL} The processor is nullptr.\n         {@link HIAPPEVENT_INVALID_PARAM_VALUE} Invalid Param value.\n         {@link HIAPPEVENT_OPERATE_FAILED} Name not found or register processor error.\n         {@link HIAPPEVENT_INVALID_UID} Invalid uid.\n @since 18"]
    #[cfg(feature = "api-18")]
    pub fn OH_HiAppEvent_AddProcessor(processor: *mut HiAppEvent_Processor) -> i64;
}
extern "C" {
    #[doc = " @brief The interface to destroy processor.\n\n @param processor The pointer to the HiAppEvent_Processor instance.\n @since 18"]
    #[cfg(feature = "api-18")]
    pub fn OH_HiAppEvent_DestroyProcessor(processor: *mut HiAppEvent_Processor);
}
extern "C" {
    #[doc = " @brief The interface to remove processor.\n\n @param processorId The id of the processor.\n @return set result.\n         {@link HIAPPEVENT_SUCCESS} The operation is successful.\n         {@link HIAPPEVENT_PROCESSOR_NOT_FOUND} Processor not add.\n         {@link HIAPPEVENT_OPERATE_FAILED} The operation is failed.\n         {@link HIAPPEVENT_INVALID_UID} Invalid uid.\n @since 18"]
    #[cfg(feature = "api-18")]
    pub fn OH_HiAppEvent_RemoveProcessor(processorId: i64) -> ::std::os::raw::c_int;
}
extern "C" {
    #[doc = " @brief Create a HiAppEvent_Config handler pointer to set the config.\n\n @return Returns a pointer to the HiAppEvent_Config instance.\n @since 15"]
    #[cfg(feature = "api-15")]
    pub fn OH_HiAppEvent_CreateConfig() -> *mut HiAppEvent_Config;
}
extern "C" {
    #[doc = " @brief Destroy the specified HiAppEvent_Config handle resource.\n\n @param config The pointer to the HiAppEvent_Config instance.\n @since 15"]
    #[cfg(feature = "api-15")]
    pub fn OH_HiAppEvent_DestroyConfig(config: *mut HiAppEvent_Config);
}
extern "C" {
    #[doc = " @brief The interface to set item to the config.\n\n @param config The pointer to the HiAppEvent_Config instance.\n @param itemName The name of config item.\n @param itemValue The value of config item.\n @return set result.\n         {@link HIAPPEVENT_SUCCESS} The operation is successful.\n         {@link HIAPPEVENT_EVENT_CONFIG_IS_NULL} The event config is null.\n         {@link HIAPPEVENT_INVALID_PARAM_VALUE} The item is invalid.\n @since 15"]
    #[cfg(feature = "api-15")]
    pub fn OH_HiAppEvent_SetConfigItem(
        config: *mut HiAppEvent_Config,
        itemName: *const ::std::os::raw::c_char,
        itemValue: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    #[doc = " @brief The interface to set the config.\n\n @param name The name of the os event.\n @param config The pointer to the HiAppEvent_Config instance.\n @return set result.\n         {@link HIAPPEVENT_SUCCESS} The operation is successful.\n         {@link HIAPPEVENT_INVALID_PARAM_VALUE} The config is invalid.\n @since 15"]
    #[cfg(feature = "api-15")]
    pub fn OH_HiAppEvent_SetEventConfig(
        name: *const ::std::os::raw::c_char,
        config: *mut HiAppEvent_Config,
    ) -> ::std::os::raw::c_int;
}
