//! Typed AbilityKit extended Native child-process access.
//!
//! Feature gates follow runtime API availability, not the build SDK. Pure
//! validation and registry tests run on Unix hosts without an OHOS linker.
//! Platform methods on a non-OHOS host return [`NativeChildProcessError::HostUnsupported`].
//! This crate does not implement independent-process configuration or Binder IPC.

mod error;
pub use error::NativeChildProcessError;

#[cfg(feature = "api-13")]
mod args;
#[cfg(feature = "api-20")]
mod configs;
#[cfg(feature = "api-13")]
mod entry;
#[cfg(all(feature = "api-13", any(target_env = "ohos", test)))]
mod list;
#[cfg(feature = "api-13")]
mod manager;
#[cfg(feature = "api-20")]
mod registry;
#[cfg(feature = "api-13")]
mod types;

#[cfg(feature = "api-13")]
pub use args::ChildProcessArgsBuilder;
#[cfg(feature = "api-20")]
pub use configs::{ChildProcessConfigs, ChildProcessName};
#[cfg(feature = "api-13")]
pub use entry::ChildLaunchArgs;
#[cfg(feature = "api-13")]
pub use manager::{ChildProcessHandle, NativeChildProcessManager};
#[cfg(feature = "api-20")]
pub use registry::{ChildExitOutcome, ChildProcessExitEvent, ChildProcessExitSubscription};
#[cfg(feature = "api-13")]
pub use types::{
    ChildFdName, ChildProcessEntry, ChildProcessId, ChildProcessOptions, IsolationMode,
};

/// Explicit raw/unsafe Binder boundary. No ownership-safe IPC facade is claimed.
/// All functions retain the sys crate's unsafe contract, including remote-proxy
/// destruction by IPCKit (which is not supplied by this binding).
#[cfg(all(feature = "raw-ipc", target_env = "ohos"))]
pub mod raw_ipc {
    #[cfg(feature = "api-20")]
    pub use ohos_native_child_process_sys::OH_Ability_CreateNativeChildProcessWithConfigs;
    pub use ohos_native_child_process_sys::{
        OHIPCRemoteProxy, OH_Ability_CreateNativeChildProcess,
        OH_Ability_OnNativeChildProcessStarted,
    };
}

/// Implementation detail used by the entry macro; not an application API.
#[doc(hidden)]
#[cfg(all(feature = "api-13", target_env = "ohos"))]
pub mod __private {
    pub use crate::entry::run_child_entry;
    pub use ohos_native_child_process_sys::NativeChildProcess_Args as RawArgs;
}

/// Exports the exact Native entry ABI and contains decoding/handler panics.
/// The handler takes `ChildLaunchArgs<'_>` and returns
/// `Result<(), NativeChildProcessError>`. Return ends the child; it must block
/// while child work is alive. Compile this only in the packaged child library.
#[cfg(all(feature = "api-13", target_env = "ohos"))]
#[macro_export]
macro_rules! native_child_entry {
    ($symbol:ident, $handler:path) => {
        /// AbilityKit Native child entry, generated by the binding adapter.
        ///
        /// # Safety
        /// Called only by AbilityKit with valid invocation-scoped SDK arguments
        /// and uniquely delivered descriptors in the current child process.
        #[unsafe(no_mangle)]
        pub unsafe extern "C" fn $symbol(args: $crate::__private::RawArgs) {
            // SAFETY: AbilityKit supplies its entry arguments for this one entry
            // invocation. The adapter owns FD decoding and catches all panics.
            // Do not perform fallible formatting/logging after panic containment
            // at the C boundary. Returning on error terminates the child.
            let _ = unsafe { $crate::__private::run_child_entry(args, $handler) };
        }
    };
}

#[cfg(all(test, feature = "api-13"))]
pub(crate) static FD_TEST_LOCK: std::sync::Mutex<()> = std::sync::Mutex::new(());

#[cfg(feature = "api-13")]
pub(crate) fn contain_panic<T>(callback: impl FnOnce() -> T) -> Result<T, NativeChildProcessError> {
    match std::panic::catch_unwind(std::panic::AssertUnwindSafe(callback)) {
        Ok(value) => Ok(value),
        Err(payload) => {
            // A user-provided panic payload may itself panic in Drop. Never let
            // that second panic cross an FFI boundary.
            std::mem::forget(payload);
            Err(NativeChildProcessError::CallbackPanicked)
        }
    }
}
