/* auto-generated by OHOS-RS */
/* eslint-disable */

/**
 * Clone/modify/readback report of the most recent UI input event (see
 * CLONED). Empty until the first event arrives.
 */
export declare function lastClonedEvent(): string;

export declare function lastEvent(): string;
