/* auto-generated by OHOS-RS */
/* eslint-disable */

export declare function capture(): string;

/**
 * Explicitly drop the camera session (the surface stays alive; the next
 * reopen_session brings it back).
 */
export declare function closeSession(): string;

export declare function lastResult(): string;

/**
 * Drop the camera session and reopen it against the current surface. The
 * binding's CameraInstanceLease serializes camera access, so this exercises
 * the full close -> reopen lifecycle in one process.
 */
export declare function reopenSession(): string;

export declare function sessionInfo(): string;

export declare function switchFlash(on: boolean): string;
