/* auto-generated by OHOS-RS */
/* eslint-disable */

export declare function bigintRoundtrip(value: string): string;

export declare function bufferRoundtrip(): Array<number>;

export declare function evalInJsvm(script: string): string;

export declare function exceptionMessage(): string;

export declare function externalRoundtrip(): string;

export declare function jsonRoundtrip(): string;

export declare function nativeMethodWithData(): string;

export declare function objectKeys(): Array<string>;

export declare function objectRoundtrip(): string;

export declare function promiseRoundtrip(): boolean;

export declare function typeTagRoundtrip(): boolean;

export declare function typedArrayRoundtrip(): Array<number>;

export declare function wrapRoundtrip(): boolean;
