/* auto-generated by OHOS-RS */
/* eslint-disable */

/** Arms four live children; the E2E host then terminates their parent. */
export declare function armParentExitProbe(): Promise<string>;

/** Runs a binding scenario on a native worker with real child processes. */
export declare function runBindingProbe(scenario: string): Promise<string>;

/** Exercises native configs, including the assigned child process name. */
export declare function runConfiguredProbe(forced: boolean): Promise<string>;

/** Observes and terminates an ArkTS-started child using the Rust binding. */
export declare function runInteropProbe(pid: number, kind: string): Promise<string>;

/** Runs all blocking platform/socket work on a libuv worker, not ArkUI. */
export declare function runProbe(forced: boolean): Promise<string>;
