/* auto-generated by OHOS-RS */
/* eslint-disable */

export declare function currentQos(): string;

export declare function resetQos(): void;

export declare function setQos(level: string): void;

export declare function smoke(): string;
