/* auto-generated by OHOS-RS */
/* eslint-disable */

export declare function drawXcomponent(): void;

/** Constrain the expected frame rate range of the surface's frame callbacks. */
export declare function setFrameRate(min: number, max: number, expected: number): void;

/**
 * Surface lifecycle counters for the E2E suite (see SURFACE_EVENTS).
 * `created`/`destroyed` count OnSurfaceCreated/OnSurfaceDestroyed events
 * across every XComponent instance bound to this library; `lastW`/`lastH`
 * are the pixel size of the most recent created surface.
 */
export declare function surfaceEvents(): string;
