/* auto-generated by OHOS-RS */
/* eslint-disable */

/**
 * Per-id `created/destroyed` counters joined by ';', ids sorted. Empty when
 * no surface has been created yet.
 */
export declare function eventsById(): string;

export declare function resetEvents(): void;
