[package]
name                   = "native_child_process_example"
version                = "0.1.0"
edition.workspace      = true
rust-version.workspace = true
publish                = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
ohos-native-child-process-binding = { workspace = true }

[target.'cfg(target_env = "ohos")'.dependencies]
napi-ohos        = { workspace = true }
napi-derive-ohos = { workspace = true }

[build-dependencies]
napi-build-ohos = { workspace = true }

[features]
default = ["api-22"]
api-22  = ["ohos-native-child-process-binding/api-22"]
api-26  = ["api-22", "ohos-native-child-process-binding/api-26"]

[lints]
workspace = true
